- frontend/src/assets/svg/checkedbox_circle.svg
- frontend/src/pages/seeker/auth/SeekerLoginPage.css
- frontend/src/pages/seeker/auth/SeekerLoginPage.vue
#87 
<br>
css에 svg 경로가 안맞아서 화면이 깨져 나오는 부분 수정하였습니다.
Resolves: #87 
<br>
지원자 로그인 페이지 디자인 수정
<br>
<br>
> [Fix] 지원자 로그인 페이지 css 에러 해결

- backend/build.gradle
- backend/src/main/java/com/sabujaks/irs/domain/auth/controller/AuthController.java
- backend/src/main/java/com/sabujaks/irs/domain/auth/model/entity/EmailVerify.java
- backend/src/main/java/com/sabujaks/irs/domain/auth/model/response/AuthSignupRes.java
- backend/src/main/java/com/sabujaks/irs/domain/auth/repository/EmailVerifyRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/auth/service/AuthService.java
- backend/src/main/java/com/sabujaks/irs/domain/auth/service/EmailVerifyService.java
- backend/src/main/java/com/sabujaks/irs/global/common/exception/GlobalExceptionHandler.java
- backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
closed: #2 
<br>
채용담당자 이메일 검증 기능 개발
<br>
채용담당자가 회원가입시에 이메일을 통해 인증 링크를 보내고, 백엔드에서 이를 검증하고
해당 회원의 enabled를 1로 변경해 인증을 완료
<br>
> [#2][Feat] 채용담당자 이메일 검증 개발

- backend/src/main/java/com/sabujaks/irs/domain/auth/model/request/AuthLoginReq.java
- backend/src/main/java/com/sabujaks/irs/domain/test/TestController.java
- backend/src/main/java/com/sabujaks/irs/global/common/exception/GlobalExceptionHandler.java
- backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
- backend/src/main/java/com/sabujaks/irs/global/config/SecurityConfig.java
- backend/src/main/java/com/sabujaks/irs/global/security/CustomUserDetailService.java
- backend/src/main/java/com/sabujaks/irs/global/security/CustomUserDetails.java
- backend/src/main/java/com/sabujaks/irs/global/security/exception/CustomAccessDeniedHandler.java
- backend/src/main/java/com/sabujaks/irs/global/security/exception/CustomAuthenticationEntryPoint.java
- backend/src/main/java/com/sabujaks/irs/global/security/exception/CustomLoginFailureHandler.java
- backend/src/main/java/com/sabujaks/irs/global/security/filter/JwtFilter.java
- backend/src/main/java/com/sabujaks/irs/global/security/filter/LoginFilter.java
- backend/src/main/java/com/sabujaks/irs/global/utils/JwtUtil.java
closed: #4   
<br>
채용담당자 로그인 기능 개발
<br>
1. 스프링 시큐리티 Login 필터, Jwt 필터 개발 및 token 조작을 위한 jwtUtil 클래스 구현하고, AccessToken을 발급해 쿠키에 저장
2. CustomAccessDeniedHandler, CustomAuthenticationEntryPoint, CustomLoginFailureHandler를 구현해 예외를 GlobalExceptionHandler로 처리
<br>
> [#4][Feat] 채용담당자 로그인 개발 완료

- backend/src/main/java/com/sabujaks/irs/domain/auth/service/AuthService.java
closed: #6 
<br>
지원자 이메일 인증 기능 개발
<br>
1. 지원자가 회원가입시에 이메일 링크를 통해 인증
2. 백엔드에서 링크로 받은 Get요청을 서비스단에서 검증하고 해당 회원의 email_auth를 1로 변경해 인증을 완료
<br>
> [#6][Feat] 지원자 이메일 인증 개발

- backend/src/main/java/com/sabujaks/irs/domain/auth/model/request/AuthLoginReq.java
- backend/src/main/java/com/sabujaks/irs/global/security/CustomUserDetailService.java
- backend/src/main/java/com/sabujaks/irs/global/security/filter/LoginFilter.java
closed: #7 
<br>
지원자 일반 로그인 기능 개발
<br>
1. 스프링 시큐리티 Login, Jwt 필터 개발 및 token 조작 jwtUtil 구현
2. AccessToken을 발급해 쿠키에 저장
3. CustomAccessDeniedHandler, CustomAuthenticationEntryPoint, CustomLoginFailureHandler를 구현
4. CustomUserDetailService에서 DB 조회시 채용담당자보단 지원자가 압도적으로 조회수가 많으므로 분기 변경
<br>
<br>
> [#7][Feat] 지원자 일반 로그인 개발

- frontend/public/css/AnnounceRegisterStep1Page.css
- frontend/src/components/recruiter/MainSideBarComponent.vue
- frontend/src/pages/recruiter/announce/AnnounceRegisterStep1Page.vue
- frontend/src/router/index.js
#87 
<br>
announce-register-step1 page 이관 과정에서 생긴 css 충돌 해결했습니다.
<br>
- announce-register-step1페이지 css 에러 해결
<br>
<br>
> [#87][Fix] announce-register-step1 markup vue 이관

- backend/build.gradle
- backend/src/main/java/com/sabujaks/irs/domain/auth/model/entity/Seeker.java
- backend/src/main/java/com/sabujaks/irs/global/config/SecurityConfig.java
- backend/src/main/java/com/sabujaks/irs/global/security/oauth2/CustomOAuth2UserDetails.java
- backend/src/main/java/com/sabujaks/irs/global/security/oauth2/CustomOAuth2UserService.java
- backend/src/main/java/com/sabujaks/irs/global/security/oauth2/GoogleUserDetails.java
- backend/src/main/java/com/sabujaks/irs/global/security/oauth2/KakaoUserDetails.java
- backend/src/main/java/com/sabujaks/irs/global/security/oauth2/NaverUserDetails.java
- backend/src/main/java/com/sabujaks/irs/global/security/oauth2/OAuth2AuthenticationSuccessHandler.java
- backend/src/main/java/com/sabujaks/irs/global/security/oauth2/OAuth2UserInfo.java
- backend/src/main/resources/application.yml
closed: #8 
<br>
지원자 소셜 로그인 기능 개발
<br>
1. Spring Oauth2를 이용해 구현
2. Oauth2User, UserDetails를 상속받은 CustomOAath2UserDetails 구현
3. CustomOAuth2UserService를 이용해 OAuth2User의 정보를 Seeker 테이블에 저장
4. OAuth2UserInfo 클래스를 구현하고 상속받아 카카오, 네이버, 구글 소셜 로그인 구현
> [#8][Feat] 지원자 소셜 로그인 개발

- backend/src/main/java/com/sabujaks/irs/global/config/SecurityConfig.java
closed: #9  
<br>
지원자, 채용담당자 로그아웃 기능 개발
<br>
1. 스프링 시큐리티에서 로그아웃을 구현
2. 로그아웃시 .deleteCookies로 쿠키값을 삭제
> [#9][Feat] 로그아웃 개발

- frontend/src/App.css
- frontend/src/components/seeker/SeekerHeaderComponent.vue
- frontend/src/components/seeker/SeekerSideBarComponent.vue
- frontend/src/pages/seeker/announce/AnnounceDetailPage.vue
- frontend/src/pages/seeker/announce/AnnounceReadAllPage.vue
- frontend/src/pages/seeker/mypage/MypageAnnouceResumePage.vue
- frontend/src/pages/seeker/mypage/MypageIntegrationeResumePage.vue
- frontend/src/pages/seeker/mypage/MypageMainPage.vue
- frontend/src/pages/seeker/mypage/MypageNotificationPage.vue
- frontend/src/pages/seeker/mypage/MypageSchedulePage.vue
#87
<br>
지원자 쪽 전체 페이지를 컴포넌트화 하고 css 수정
<br>
뷰 이관 및 수정
<br>
<br>
> [Fix] seeker 부분 컴포넌트, css 수정

- .gitignore
- cicd/docker-compose.yml
- cicd/nginx/default.conf
closed: #107 
<br>
Docker-Compose 개발환경 설정을 수행
<br>
1. cicd 설정
2. 1. docker-copose.yml 설정
3. Mariadb, Backend, Frontend 도커로 개발환경 설정
> [#107][Init] Docker-compose 개발 환경 설정

- backend/src/main/java/com/sabujaks/irs/domain/auth/model/entity/Seeker.java
- backend/src/main/java/com/sabujaks/irs/domain/auth/repository/SeekerRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/controller/ResumeController.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/entity/PersonalInfo.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/entity/PreferentialEmp.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/entity/ResumeInfo.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/request/PersonalInfoCreateReq.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/request/PreferentialEmpInfoCreateReq.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/request/ResumeCreateReq.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/response/ResumeCreateRes.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/repository/PersonalInfoRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/repository/PreferentialEmpRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/repository/ResumeInfoRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/service/ResumeService.java
- backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
closed: #37
<br>
지원자 지원서 등록 1 기능 개발 완료
<br>
지원정보, 인적사항, 취업우대 • 병역 테이블 생성 및 테이블에 데이터 저장
<br>
<br>
> [Feat] 지원자 지원서 등록1 기능 개발 완료

- frontend/src/components/recruiter/MainHeaderComponent.vue
- frontend/src/pages/recruiter/interview-schedule/InterviewScheduleMainPage.vue
- frontend/src/stores/UseInterviewScheduleStore.js
- frontend/vue.config.js
#82 
<br>
채용담당자가 면접자들을 선택 및 날짜를 지정해서 면접일정을 등록할 수 있는 기능 개발 완료했습니다.
<br>
- 면접 일정 등록 개발
<br>
<br>
> [#82][Feat] 채용담당자 면접 일정 생성 개발

- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/controller/InterviewScheduleController.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/entity/InterviewSchedule.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/request/InterviewScheduleReq.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/response/InterviewScheduleRes.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/repository/InterviewScheduleRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/service/InterviewScheduleService.java
- backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
- backend/src/main/java/com/sabujaks/irs/global/config/SecurityConfig.java
- backend/src/main/java/com/sabujaks/irs/global/utils/EmailSender.java
#47 
<br>
채용담당자가 신입 면접자들을 선택 및 날짜를 지정해서 면접일정을 등록할 수 있는 기능 개발 완료했습니다.
<br>
- 면접 일정 엔티티 설계
- 면접 일정 등록 개발
- 면접 일정 저장 개발
- 면접 등록 후 이메일 발송
<br>
<br>
> [#47][Feat] 채용담당자 면접 일정 생성 개발

- backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
> [Fix] BaseResponseMessage  기호 수정

- backend/src/main/java/com/sabujaks/irs/domain/data_init/DataInit.java
- backend/src/main/java/com/sabujaks/irs/domain/data_init/entity/BaseInfo.java
- backend/src/main/java/com/sabujaks/irs/domain/data_init/repository/BaseInfoRepository.java
#115
<br>
지원서 폼 조립 시에 기준 코드가 필요하여 base_info 테이블 생성 및 필요 데이터 설정했습니다.
<br>
기준코드 테이블 생성 및 데이터 설정
<br>
<br>
> [Feat] data init 테이블 생성, 지원서 폼 관련 데이터 설정

- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/entity/InterviewSchedule.java
- backend/src/main/java/com/sabujaks/irs/domain/video_interview/controller/VideoInterviewController.java
- backend/src/main/java/com/sabujaks/irs/domain/video_interview/mdoel/entity/VideoInterview.java
- backend/src/main/java/com/sabujaks/irs/domain/video_interview/mdoel/request/VideoInterviewCreateReq.java
- backend/src/main/java/com/sabujaks/irs/domain/video_interview/mdoel/response/VideoInterviewCreateRes.java
- backend/src/main/java/com/sabujaks/irs/domain/video_interview/mdoel/response/VideoInterviewSearchRes.java
- backend/src/main/java/com/sabujaks/irs/domain/video_interview/repository/VideoInterviewRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/video_interview/service/VideoInterviewService.java
- backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
- frontend/src/pages/recruiter/video-interview/VideoInterViewTest2Page.vue
- frontend/src/stores/UseVideoInterviewStore.js
closed: #118 
<br>
지원자, 면접진 화상 면접방 목록 조회 기능 개발
<br>
1. OpenVidu를 사용해 화상 면접 기능을 구현
2. VideoInterViewRoom 테이블의 공고 UUID를 이용해 저장된 값을 전체 조회해서 화상 면접방 리스트를 가져옴
3. Vue 테스트 페이지 구현
> [Feat] 지원자, 면접진 화상 면접방 목록 조회 개발

- backend/src/main/java/com/sabujaks/irs/domain/resume/model/entity/Education.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/entity/PersonalHistory.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/entity/PersonalInfo.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/entity/PreferentialEmp.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/entity/ResumeInfo.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/request/EducationCreateReq.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/request/PersonalHistoryCreateReq.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/request/ResumeCreateReq.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/repository/EducationRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/repository/PersonalHistoryRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/service/ResumeService.java
closed: #38
<br>
지원자 지원서 등록 2 기능 개발 완료
<br>
학력, 경력 테이블 생성 및 테이블에 데이터 저장
<br>
<br>
> [Feat] 지원자 지원서 등록2 기능 개발 완료

- backend/src/main/java/com/sabujaks/irs/domain/resume/controller/ResumeController.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/entity/Award.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/entity/Certification.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/entity/ResumeInfo.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/entity/Training.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/request/AwardCreateReq.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/request/CertificationCreateReq.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/request/ResumeCreateReq.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/request/TrainingCreateReq.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/repository/AwardRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/repository/CertificationRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/repository/TrainingRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/service/ResumeService.java
closed: #40 
<br>
지원자 지원서 등록 4 기능 개발 완료
<br>
자격증, 교육이수, 수상 테이블 생성 및 테이블에 데이터 저장
<br>
<br>
> [Feat] 지원자 지원서 등록4 개발 완료

- backend/src/main/java/com/sabujaks/irs/domain/announce/model/entity/Announcement.java
- backend/src/main/java/com/sabujaks/irs/domain/auth/model/entity/Seeker.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/controller/ResumeController.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/entity/CustomLetter.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/entity/CustomResumeInfo.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/entity/Portfolio.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/entity/Resume.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/entity/ResumeInfo.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/request/CustomLetterCreateReq.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/request/PortfolioCreateReq.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/request/ResumeCreateReq.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/repository/CustomLetterRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/repository/CustomResumeInfoRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/repository/PortfolioRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/repository/ResumeRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/service/ResumeService.java
closed: #41 
<br>
지원자 지원서 등록 5 기능 개발 완료
<br>
자기소개서, 포트폴리오 테이블 생성 및 테이블에 데이터 저장
맞춤 지원정보 테이블에 지원자가 커스텀한 지원서 항목의 맞춤코드를 저장
<br>
<br>
> [#41][Feat] 지원자 지원서 등록5 개발 완료

- backend/src/main/java/com/sabujaks/irs/domain/data_init/DataInit.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/controller/InterviewScheduleController.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/entity/InterviewSchedule.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/entity/InterviewScheduleLists.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/entity/Team.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/request/InterviewScheduleReq.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/response/InterviewScheduleListsRes.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/repository/InterviewScheduleListsRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/repository/InterviewScheduleRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/repository/TeamRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/service/InterviewScheduleService.java
- backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
- backend/src/main/java/com/sabujaks/irs/global/utils/EmailSender.java
closed #47  
<br>
각 면접일정 생성시, 팀마다, 날짜마다, 고유 uuid를 생성해 면접방을 관리할 수 있게 개발하였습니다.
<br>
- Team 엔티티 설계
- InterviewScheduleList 엔티티 설계
- 면접 일정, 팀간 uuid 생성
- 이메일 전송 로직 변경
<br>
<br>
> [#47][Feat] 채용 담당자 신입 지원자 면접 일정 등록 

- backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
#134  
<br>
BaseResponse 누락 부분 수정했습니다.
<br>
- BaseResponse 수정
<br>
<br>
> [#134][Fix] 면접 일정 baseresponse 수정

- backend/src/main/java/com/sabujaks/irs/domain/data_init/DataInit.java
- backend/src/main/java/com/sabujaks/irs/domain/data_init/entity/BaseInfo.java
#139 
<br>
기준코드를 사용하는 서비스 부분에서 필요한 데이터 입력과 코드 개발
<br>
<br>
기준코드 테이블 필드 변경 및 데이터 업데이트
<br>
> [#139][Feat] BaseInfo 테이블 필드 변경 후 복리후생 데이터 입력

- backend/build.gradle
- backend/src/main/java/com/sabujaks/irs/domain/alarm/controller/AlarmController.java
- backend/src/main/java/com/sabujaks/irs/domain/alarm/model/entity/Alarm.java
- backend/src/main/java/com/sabujaks/irs/domain/alarm/model/request/AlarmReq.java
- backend/src/main/java/com/sabujaks/irs/domain/alarm/model/response/AlarmRes.java
- backend/src/main/java/com/sabujaks/irs/domain/alarm/repository/AlarmRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/alarm/service/AlarmService.java
- backend/src/main/java/com/sabujaks/irs/domain/auth/model/entity/Seeker.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/controller/InterviewScheduleController.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/response/InterviewScheduleRes.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/repository/InterviewScheduleRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/service/InterviewScheduleService.java
- backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
- backend/src/main/java/com/sabujaks/irs/global/utils/EmailSender.java
- backend/src/main/resources/templates/InterviewEmail.html
closed #54 
<br>
경력 지원자에 한해서, 면접 일정이 등록되면, 해당 면접 일정에 만약 면접 진행이 불가한 경우를 생각해서 면접 일정 조율 기능 개발중에 있습니다.
<br>
- Alarm 엔티티 설계
- 알림 리스트에서 면접 일정 조율 캘린더 모달창 구현
- 알림 등록
- 알림 조회
- 알림 관련 baseresponse 추가
<br>
<br>
> [#54][Feat] 경력 면접 일정 조율 기능 개발

- backend/src/main/java/com/sabujaks/irs/domain/video_interview/model/response/VideoInterviewSearchRes.java
- backend/src/main/java/com/sabujaks/irs/domain/video_interview/service/VideoInterviewService.java
- frontend/src/pages/video-interview/VideoInterviewMainPage.vue
#87 
<br>
화상 면접방 메인 페이지 수정
<br>
1. 화상 면접방 메인 페이지 수정
2. 공고제목을 불러와야 함
> [#87][Fix] 화상 면접방 메인 페이지 수정

- backend/src/main/java/com/sabujaks/irs/domain/auth/controller/AuthController.java
- backend/src/main/java/com/sabujaks/irs/domain/auth/model/entity/Estimator.java
- backend/src/main/java/com/sabujaks/irs/domain/auth/model/response/UserInfoGetRes.java
- backend/src/main/java/com/sabujaks/irs/domain/auth/repository/EstimatorRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/auth/service/AuthService.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/entity/InterviewParticipate.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/response/InterviewParticipateRes.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/response/InterviewScheduleRes.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/service/InterviewScheduleService.java
- backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
- backend/src/main/java/com/sabujaks/irs/global/config/SecurityConfig.java
- backend/src/main/java/com/sabujaks/irs/global/security/CustomUserDetailService.java
- backend/src/main/java/com/sabujaks/irs/global/security/CustomUserDetails.java
- backend/src/main/java/com/sabujaks/irs/global/security/filter/JwtFilter.java
- backend/src/main/java/com/sabujaks/irs/global/security/filter/LoginFilter.java
- frontend/src/pages/video-interview/VideoInterviewMainPage.vue
- frontend/src/pages/video-interview/VideoInterviewRoomPage.vue
- frontend/src/stores/UseVideoInterviewStore.js
closed: #147
<br>
유저 정보 조회 기능 수정
<br>
1. 유저 정보 조회 토큰방식 -> 컨트롤러 방식(이유: 스프링 방화벽에서 암호문이아니면 request를 거부함)
<br>
> [#134][Fix] 유저 정보 조회 기능 수정

- backend/src/main/java/com/sabujaks/irs/domain/auth/controller/AuthController.java
- backend/src/main/java/com/sabujaks/irs/domain/auth/service/AuthService.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/repository/InterviewScheduleRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/video_interview/service/VideoInterviewService.java
- backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
- backend/src/main/resources/application.yml
- frontend/src/pages/video-interview/VideoInterviewMainPage.vue
- frontend/src/pages/video-interview/VideoInterviewRoomPage.vue
- frontend/src/stores/UseAuthStore.js
closed: #59 #134 
<br>
지원자, 면접진 화상 면접방 참여 기능 수정
<br>
1. 지원자, 면접진 화상 면접방 참여 기능 수정
2. 클라이언트 접속이 없을땐 세션이 유지되지만 한개의 연결이 생기고 끊으면 세션은 종료
3. 따라서 세션이 종료되도 연결시에 다시 재생성하게 수정
> [#134][Fix] 지원자, 면접진 화상 면접방 참여 기능 수정

- frontend/src/router/index.js
closed: #71 
<br>
지원자 지원서 등록 페이지 개발 완료
<br>
router/index.js 수정
<br>
<br>
> [#71][Fix] router 수정

- frontend/src/router/index.js
closed #177 
<br>
구버전 라우터 삭제
<br>
1. Merge가운데 재생성된 구버전 라우터 삭제
> [#177][Fix] index.js 구버전 라우터 삭제

- backend/src/main/java/com/sabujaks/irs/domain/announcement/model/entity/Announcement.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/controller/InterviewEvaluateController.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/model/entity/InterviewEvaluateForm.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/model/entity/InterviewEvaluateResult.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/model/response/InterviewEvaluateFormReadRes.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/repository/InterviewEvaluateFormRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/service/InterviewEvaluateService.java
- backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
closed #179 
<br>
화상 면접방에서 면접자가 평가할 평가표 조회
<br>
1. InterviewEvaluate, InterviewEvaluateForm, InterviewEvaluateResult 엔티티, 연관관계 매핑생성
2. Announcement, InterviewEvaluteForm announceUUID로 연관관계 매핑
3. announcementUUID로 InterviewEvaluteForm을 가져옴
> [#179][Feat] 면접관 화상 면접 평가표 조회 개발

- backend/src/main/java/com/sabujaks/irs/domain/announcement/controller/AnnouncementController.java
- backend/src/main/java/com/sabujaks/irs/domain/announcement/model/request/CustomFormCreateReq.java
- backend/src/main/java/com/sabujaks/irs/domain/announcement/model/response/AnnouncementReadAllRes.java
- backend/src/main/java/com/sabujaks/irs/domain/announcement/model/response/AnnouncementReadDetailRes.java
- backend/src/main/java/com/sabujaks/irs/domain/announcement/service/AnnouncementService.java
- backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
- frontend/src/pages/recruiter/announce/AnnounceRegisterStep1Page.vue
closed #35
<br>
지원자, 또는 모두가 전체 공고를 조회하는 기능입니다.
<br>
[공고 등록] 기능 수정 / 공고 이미지 저장 시, 글자로 저장되는 정보 추가
[공고 전체 조회] 기능 개발 / (지원자 입장에서, 모두 볼 수 있음) - res req 서비스 컨트롤러 추가
<br>
<br>
> [#35][Feat] 지원자 공고 전체 조회 기능 개발

- backend/src/main/java/com/sabujaks/irs/domain/data_init/DataInit.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/service/InterviewEvaluateService.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/repository/InterviewParticipateRepository.java
- backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
- frontend/src/pages/video-interview/VideoInterviewRoomPage.vue
- frontend/src/stores/UseInterviewEvaluateStore.js
#159 
<br>
화상 면접 페이지에서 면접 방에 참여하면 나오는 면접관 페이지 개발
<br>
1. 채용담당자가 등록한 공고의 면접 평가표를 가져옴
> [#159][Feat] 화상 면접 면접관 페이지 개발

- backend/src/main/java/com/sabujaks/irs/domain/announcement/controller/AnnouncementController.java
- backend/src/main/java/com/sabujaks/irs/domain/announcement/model/response/AnnouncementReadDetailRes.java
- backend/src/main/java/com/sabujaks/irs/domain/announcement/service/AnnouncementService.java
closed #36
<br>
지원자 공고 상세 조회 기능 개발했습니다.
<br>
지원자 페이지에서 보는 공고 전체 조회에서 각 공고 클릭 시 필요한 상세조회.
- 상세조회 announcementReadDetailRes 기업 정보 추가
공고 등록과 지원서 폼 등록, 공고에 필요한 데이터 조회 부분 컨트롤러 매개변수를 커스텀유저가 들어가야하는 부분이 있어서 약간 수정.
<br>
<br>
> [#36][Feat] 지원자 공고 상세 조회 개발

- frontend/src/assets/css/grid.css
- frontend/src/components/recruiter/InterviewScheduleList.vue
- frontend/src/components/recruiter/InterviewScheduleMain.vue
- frontend/src/pages/recruiter/interview-schedule/InterviewScheduleMainExp.vue
- frontend/src/stores/UseInterviewScheduleStore.js
closed #193 
<br>
각 공고 면접 일정 조회에 있어, 
등록된 공고 조회 & 그 공고에 맞는 면접일정 조회 페이지 개발
<br>
1. 채용담당자가 등록한 공고를 조회할 수 있음
2. 각 공고에 등록된 각 면접 일정을 조회할 수 있음
> [#193][Feat] 공고조회 & 면접 일정 조회

- frontend/src/components/seeker/AwardComponent.vue
- frontend/src/components/seeker/CertificationComponent.vue
- frontend/src/components/seeker/CustomLetterFormComponent.vue
- frontend/src/components/seeker/EducationComponent.vue
- frontend/src/components/seeker/InternsActivityComponent.vue
- frontend/src/components/seeker/LanguageComponent.vue
- frontend/src/components/seeker/PersonalHistoryComponent.vue
- frontend/src/components/seeker/PersonalInfoComponent.vue
- frontend/src/components/seeker/PortfolioComponent.vue
- frontend/src/components/seeker/PreferentialEmpComponent.vue
- frontend/src/components/seeker/StudyingAbroadComponent.vue
- frontend/src/components/seeker/TrainingComponent.vue
- frontend/src/pages/seeker/resume/ResumeSubmitPage.vue
- frontend/src/router/index.js
- frontend/src/stores/UseResumeStore.js
closed: #72 
<br>
지원자 지원서 제출 페이지 개발 완료
<br>
공고 상세에서 공고 idx와 함께 해당 페이지에 접근 시 해당 공고를 등록할 때 선택한 지원서 항목들과 자기소개서 맞춤 양식, 그리고 해당 지원자가 통합 지원서를 등록했다면 통합 지원서에 등록된 정보를 조회한다. (포트폴리오, 자기소개서 제외)
인적사항 컴포넌트 수정
학력 컴포넌트 수정
경력 컴포넌트 수정
인턴&대외활동 컴포넌트 수정
교육이수 컴포넌트 수정
자격증 컴포넌트 수정
수상 컴포넌트 수정
해외경험 컴포넌트 수정
어학 컴포넌트 수정
취업우대&병역 컴포넌트 수정
자기소개서 컴포넌트 수정
공고상세 -> 지원서 제출 페이지 개발
제출하기 클릭 시 백엔드로 데이터 전달
<br>
<br>
> [#72][Feat] 지원자 지원서 제출 페이지 개발 완료

- frontend/src/pages/video-interview/VideoInterviewRoomPage.vue
closed #199 
<br>
화상 면접 페이지에서 면접 방에 참여하면 나오는 면접관 페이지 수정
<br>
1. 면접 평가표 제출시 1부터 넣어야 되는데 0부터 넣어서 값이 한칸씩 밀리는 현상 수정
> [#199][Feat] 화상 면접 면접관 페이지 수정

- frontend/src/components/recruiter/InterviewScheduleMain.vue
- frontend/src/components/recruiter/MainHeaderComponent.vue
- frontend/src/components/recruiter/ReScheduleDetail.vue
- frontend/src/components/recruiter/ReScheduleList.vue
- frontend/src/pages/recruiter/auth/RecruiterLoginPage.vue
- frontend/src/pages/recruiter/interview-schedule/InterviewScheduleMainExp.vue
- frontend/src/pages/recruiter/interview-schedule/InterviewScheduleMainNew.vue
- frontend/src/pages/recruiter/interview-schedule/ReScheduleMainExp.vue
- frontend/src/stores/UseInterviewScheduleStore.js
- frontend/src/stores/UseUserStore.js
#81 
<br>
일정 조율 요청 페이지 개발
일정 조율 요청 기능 연동
<br>
1. 채용담당자가 등록한 면접에 일정 변경을 요청한 내역을 확인할 수 있음
2. 면접 일정요청을 참고하여 가능한 날짜로 확정 및 변경할 수 있음
> [#81][Feat] 일정조율 페이지 개발 및 기능 연동 완료

- backend/src/main/java/com/sabujaks/irs/domain/resume/controller/ResumeController.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/response/ResumeReadIntegratedRes.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/service/ResumeService.java
closed: #44 
<br>
채용담당자 또는 지원자가 공고에 지원한 지원자의 지원서를 상세 조회
<br>
응답 dto에 지원 날짜와 지원서 제목 추가
<br>
<br>
> [#44][Fix] 지원서 상세 조회 응답 dto 수정

- cicd/jenkins/backend/Dockerfile
- cicd/jenkins/backend/Jenkinsfile
- cicd/jenkins/frontend/Dockerfile
- cicd/jenkins/frontend/Jenkinsfile
- cicd/k8s/backend/backend-deployment-blue.yml
- cicd/k8s/backend/backend-deployment-green.yml
- cicd/k8s/frontend/frontend-deployment-blue.yml
- cicd/k8s/frontend/frontend-deployment-green.yml
closed: #212  
<br>
Jenkins와 k8s 배포 파일 설정을 진행
<br>
1. backend Jenkinsfile, Dockerfile 설정
2. frontend Jenkinsfile, Dockerfile 설정
3. 무중단 배포 blue, green 파일 설정
> [#212][Init] Jenkins, k8s 배포 파일 설정

- cicd/jenkins/frontend/Jenkinsfile
closed: #214   
<br>
Jenkins clone url 수정
<br>
1. frontend Jenkinsfile git clone url 수정
> [#214][Fix] cicd jenkinsfile clone url 수정

- cicd/jenkins/backend/Jenkinsfile
closed: #215 
<br>
Jenkins clone url 수정
<br>
1. backend Jenkinsfile git clone url 수정
> [#215][Fix] cicd jenkinsfile clone url 수정

- cicd/jenkins/backend/Jenkinsfile
closed: #218   
<br>
Jenkins branch 변수명 수정
<br>
1. backend Jenkinsfile branch 변수명 수정
> [#218][Fix] Jenkins branch 변수명 수정

- cicd/jenkins/frontend/Jenkinsfile
closed: #220 
<br>
Jenkins branch 변수명 수정
<br>
1. frontend Jenkinsfile branch 변수명 수정
> [#220][Fix] Jenkins branch 변수명 수정

- cicd/jenkins/backend/Jenkinsfile
- cicd/jenkins/frontend/Jenkinsfile
#222 
<br>
Jenkins 빌드 결과 discord로 알림 전송
<br>
1. frontend Jenkinsfile discord webhook 추가
2. backend Jenkinsfile discord webhook 추가
> [#222][Feat] Jenkins 빌드 결과 discord 알람

- cicd/jenkins/backend/Jenkinsfile
- cicd/jenkins/frontend/Jenkinsfile
#222 
<br>
Jenkins 빌드 결과 discord로 알림 전송
<br>
1. frontend Jenkinsfile discord webhook 변수처리
2. backend Jenkinsfile discord webhook 변수처리
> [#222][Fix] cicd jenkinsfile discord 알림 수정

- cicd/jenkins/backend/Jenkinsfile
- cicd/jenkins/frontend/Jenkinsfile
#222 
<br>
Jenkins 빌드 결과 discord로 알림 전송
<br>
1. frontend Jenkinsfile discord webhook 변수처리
2. backend Jenkinsfile discord webhook 변수처리
> [#222][Fix] cicd jenkinsfile discord 알림 수정

- cicd/k8s/backend/backend-deployment-blue.yml
- cicd/k8s/backend/backend-deployment-green.yml
closed #227 
<br>
k8s backend Deployment 파일 ConfigMap 추가
<br>
1.  k8s backend Deployment 파일 ConfigMap 추가
> [#227][Feat] k8s backend Deployment 파일 ConfigMap 추가

- cicd/jenkins/backend/Jenkinsfile
#231
<br>
젠킨스 빌드 테스트
<br>
젠킨스 백엔드 코드 수정
<br>
<br>
> [#231][Feat] jenkins back test

- cicd/jenkins/backend/Jenkinsfile
- cicd/k8s/backend/backend-deployment-blue.yml
- cicd/k8s/backend/backend-deployment-green.yml
#231
<br>
젠킨스 빌드 테스트
<br>
젠킨스 백엔드 코드 수정2
<br>
<br>
> [#231][Feat] jenkins back test2

- cicd/jenkins/backend/Jenkinsfile
#231
<br>
젠킨스 빌드 테스트
<br>
젠킨스 백엔드 코드 수정3
<br>
<br>
> [#231][Feat] jenkins back test3

- cicd/jenkins/backend/Jenkinsfile
#231
<br>
젠킨스 빌드 테스트
<br>
젠킨스 백엔드 코드 수정4
<br>
<br>
> [Feat] jenkins back test4

- cicd/jenkins/frontend/Jenkinsfile
#231
<br>
젠킨스 빌드 테스트
<br>
젠킨스 백엔드 코드 수정5
<br>
<br>
> [Feat] jenkins back test5

- backend/src/main/java/com/sabujaks/irs/domain/test/TestController.java
#231
<br>
젠킨스 빌드 테스트
<br>
젠킨스 백엔드 코드 수정6
<br>
<br>
> [Feat] jenkins back test6

- frontend/src/pages/recruiter/resume/ResumeDetailPage.vue
- frontend/src/pages/seeker/resume/ResumeDetailPage.vue
- frontend/src/router/index.js
closed: #208 
<br>
지원자가 공고에 지원한 지원자 본인의 지원서 상세 조회
<br>
공고 지원서 idx로 공고에 지원한 지원서를 상세 조회지원서의 서류 결과 값 업데이트
<br>
<br>
> [#208][Feat] 지원자 공고지원서 상세 조회 페이지 개발 완료

- backend/src/main/java/com/sabujaks/irs/domain/test/TestController.java
- cicd/jenkins/backend/Jenkinsfile
- cicd/jenkins/frontend/Jenkinsfile
#231
<br>
젠킨스 빌드 테스트
<br>
젠킨스 알림 주석처리 코드 주석해제
<br>
<br>
> [#231][Feat] jenkins front test

- backend/src/main/java/com/sabujaks/irs/domain/resume/controller/ResumeController.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/response/ResumeReadAllRes.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/repository/ResumeRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/service/ResumeService.java
- backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
closed: #22 
<br>
지원자가 본인이 지원한 공고와 공고에 대한 지원 정보 목록을 조회
<br>
지원자 idx로 지원자가 지원한 공고와 공고에 대한 지원 정보 목록을 조회
조회정보
공고지원서 idx,
지원서제목,
지원날짜,
공고 idx,
공고제목,
공고모집시작,
공고모집마감,
기업명
<br>
> [#22][Feat] 지원자 공고지원서 목록 조회 개발 완료

- backend/src/main/java/com/sabujaks/irs/domain/test/TestController.java
#231
<br>
젠킨스 빌드 테스트
<br>
k8s backend test
<br>
<br>
> [#231][Feat] k8s test

- backend/src/main/java/com/sabujaks/irs/domain/announcement/controller/AnnouncementController.java
- backend/src/main/java/com/sabujaks/irs/domain/announcement/repository/querydsl/AnnouncementDslRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/announcement/service/AnnouncementService.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/controller/InterviewScheduleController.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/repository/querydsl/InterviewScheduleDslRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/service/InterviewScheduleService.java
closed: #247 
<br>
채용담당자가 면접일정 탭에서 각 조회 페이징 처리
<br>
- 공고 조회 페이징 처리
- 면접 일정 조회 페이징 처리
- 면접 일정 조율 조회 페이징 처리
<br>
> [#247][Feat] 면접일정 조회 페이징 처리

- frontend/src/components/recruiter/InterviewScheduleList.vue
- frontend/src/components/recruiter/InterviewScheduleMain.vue
- frontend/src/components/recruiter/ReScheduleList.vue
- frontend/src/pages/recruiter/interview-schedule/InterviewScheduleMainExp.vue
- frontend/src/pages/recruiter/interview-schedule/InterviewScheduleMainNew.vue
- frontend/src/pages/recruiter/interview-schedule/ReScheduleMainExp.vue
- frontend/src/stores/UseInterviewScheduleStore.js
closed #249 
<br>
면접일정 조회 페이지에서
공고 조회 & 면접 일정 조회 & 면접 일정 조율 조회 각 페이지당 10개씩 조회
페이징 처리
<br>
1. 공고 조회 페이징 처리
2. 면접 일정 페이징 처리
3. 면접 일정 조율 페이징 처리
> [#249][Feat] 채용담당자 면접 일정 조회 페이징 처리

- cicd/jenkins/frontend/Jenkinsfile
#252 
<br>
젠킨스 빌드 테스트
<br>
젠킨스 프론트 코드 수정
execCommand 수정
<br>
<br>
> [#252][Feat] frontend jenkinsfile execCommand 수정

- cicd/jenkins/frontend/Jenkinsfile
#252 
<br>
젠킨스 빌드 테스트
<br>
젠킨스 프론트 코드 수정
execCommand 수정
<br>
<br>
> [#252][Feat] frontend jenkinsfile execCommand 수정-2

- cicd/jenkins/frontend/Jenkinsfile
#252 
<br>
젠킨스 빌드 테스트
<br>
젠킨스 프론트 코드 수정
execCommand 수정
<br>
<br>
> [#252][Feat] frontend jenkinsfile execCommand 수정-3

- cicd/jenkins/frontend/Jenkinsfile
#252 
<br>
젠킨스 빌드 테스트
<br>
젠킨스 프론트 코드 수정
execCommand 수정
<br>
<br>
> [#252][Feat] frontend jenkinsfile execCommand 수정-4

- cicd/k8s/frontend/frontend-deployment-blue.yml
- cicd/k8s/frontend/frontend-deployment-green.yml
#231
<br>
젠킨스 빌드 테스트
<br>
젠킨스 프론트 코드 수정5
livenessProbe: 에 scheme: HTTPS  # HTTP 대신 HTTPS 추가
<br>
<br>
> [#231][Feat] jenkins front test5

- cicd/nginx/default.conf
#231
<br>
젠킨스 빌드 테스트
<br>
젠킨스 프론트 코드 수정6
<br>
<br>
> [#231][Feat] jenkins front test6

- frontend/src/components/recruiter/MainSideBarComponent.vue
- frontend/src/pages/recruiter/company/CompanyInfoPage.vue
- frontend/src/router/index.js
- frontend/src/stores/UseInterviewScheduleStore.js
- frontend/src/stores/UseMypageNotificationStore.js
#84 
<br>
채용담당자가 기업 정보를 등록할 수 있다.
<br>
1. 채용담당자 기업정보 등록 페이지
<br>
<br>
> [#84][Feat] 채용담당자 기업 정보 등록 페이지

- cicd/k8s/frontend/frontend-deployment-blue.yml
#231
<br>
젠킨스 빌드 테스트7
<br>
젠킨스 백엔드 코드 수정
<br>
<br>
> [#231][Feat] jenkins back test7

- frontend/src/pages/recruiter/company/CompanyInfoPage.vue
#84 
<br>
채용담당자가 기업 정보를 등록할 수 있다.
<br>
1. 채용담당자 기업정보 등록 페이지
<br>
<br>
> [#84][Feat] 채용담당자 기업 정보 등록 페이지 디자인 추가

- cicd/jenkins/frontend/Jenkinsfile
#252 
<br>
젠킨스 빌드 테스트
<br>
젠킨스 프론트 코드 수정
execCommand 수정
<br>
<br>
> [#252][Feat] frontend jenkinsfile execCommand 수정-5

- backend/src/main/java/com/sabujaks/irs/domain/test/TestController.java
> [Feat] 배포 테스트

- frontend/src/pages/seeker/announce/AnnounceReadAllPage.vue
#231
<br>
젠킨스 빌드 테스트
<br>
젠킨스 프론트 코드 수정8
<br>
<br>
> [#231][Feat] jenkins frontend test8

- cicd/k8s/frontend/frontend-deployment-blue.yml
- cicd/k8s/frontend/frontend-deployment-green.yml
#231
<br>
젠킨스 빌드 테스트
<br>
젠킨스 프론트 코드 수정9
<br>
<br>
> [Feat] jenkins frontend test9

- cicd/jenkins/frontend/Jenkinsfile
#252 
<br>
젠킨스 빌드 테스트
<br>
젠킨스 프론트 코드 수정
execCommand 수정
<br>
<br>
> [#252][Feat] frontend jenkinsfile execCommand 수정-6

- frontend/src/pages/seeker/mypage/MypageAnnouceResumePage.vue
- frontend/src/stores/UseResumeStore.js
Fixes: #65 
<br>
지원자가 지원한 공고 지원 목록을 조회
<br>
지원자 idx로 지원자가 지원한 공고 지원 정보 목록을 조회
+ 채용 진행 상태 조회 추가 예정
<br>
<br>
> [#65][Feat] 지원자 공고 지원 목록 페이지 개발 진행중

- frontend/src/pages/recruiter/company/CompanyInfoPage.vue
#84 
<br>
채용담당자가 기업 정보를 등록할 수 있다.
<br>
1. 채용담당자 기업정보 등록 페이지 CSS 수정
<br>
<br>
> [#84][Feat] 채용담당자 회사 정보 확인 & 수정 페이지

- backend/src/main/java/com/sabujaks/irs/domain/announcement/service/AnnouncementService.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/service/InterviewScheduleService.java
- cicd/jenkins/frontend/Jenkinsfile
closed: #247
<br>
채용담당자가 면접일정 탭에서 최신순 조회
<br>
- 각 조회 최신순으로 조회 개발
<br>
> [#247][Feat] 면접 일정 조율 각 조회 최신순

- frontend/src/pages/recruiter/announce/AnnounceRegisterStep2Page.vue
- frontend/src/stores/UseCustomFormStore.js
#77
<br>
채용담당자 지원서 폼 조립 페이지 라우터 수정했습니다.
<br>
다른 페이지로 이동하는 부분에서 이동하지 않는 코드로 수정
<br>
<br>
> [#77][Fix] 채용담당자 지원서 폼 조립 페이지 수정

- frontend/src/components/recruiter/BackBtn.vue
- frontend/src/pages/recruiter/interview-schedule/InterviewScheduleMainExp.vue
- frontend/src/stores/UseInterviewScheduleStore.js
closed: #55   
<br>
채용담당자 화상 면접방 생성 기능 개발
<br>
1. 면접 일정 리스트에서 방생성 버튼을 누르면 화상 면접방 생성
2. 기본적으로 제공하는 소켓 기능을 이용해 화상 면접방을 생성
> [#55][Feat] 채용담당자 화상 면접방 생성 개발

- frontend/src/pages/seeker/auth/SeekerLoginPage.vue
closed: #286
<br>
OAuth2 테스트
<br>
OAuth2 테스트 프론트엔드 링크 변경
> [#286][Feat] k8s OAuth2 test1

- frontend/src/components/recruiter/MainSideBarComponent.vue
- frontend/src/pages/recruiter/announce/AnnounceMainPage.vue
- frontend/src/stores/UseAnnouncementStore.js
#75
<br>
공고 조회 페이지 개발
<br>
1. 채용담당자 공고메뉴 클릭 시 열리는 메인 공고 조회 페이지
<br>
<br>
> [#75][Feat] 채용담당자 조회 페이지 개발

- backend/src/main/java/com/sabujaks/irs/domain/resume/controller/ResumeController.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/model/response/ResumeReadAllRecruiterRes.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/repository/ResumeRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/service/ResumeService.java
- backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
- backend/src/main/java/com/sabujaks/irs/global/config/SecurityConfig.java
Fixes: #283 
<br>
채용담당자가 등록한 공고에 지원한 지원자 목록 조회
<br>
공고 idx로 조회
조회 정보
공고지원서 idx
지원자 이름
서류 합불
지원서 제목
지원 날짜
<br>
<br>
> [#283][Feat] 채용담당자 공고에 지원한 지원자 목록 조회

- backend/src/main/java/com/sabujaks/irs/global/security/oauth2/OAuth2AuthenticationSuccessHandler.java
closed: #286
<br>
OAuth2 테스트
<br>
OAuth2 테스트 리다이렉트 방식에서 그냥 response만 전달
> [#286][Feat] k8s OAuth2 test3

- backend/src/main/java/com/sabujaks/irs/domain/auth/model/response/UserInfoGetRes.java
- backend/src/main/java/com/sabujaks/irs/domain/auth/service/AuthService.java
- backend/src/main/java/com/sabujaks/irs/global/security/oauth2/OAuth2AuthenticationSuccessHandler.java
- frontend/src/components/seeker/SeekerHeaderComponent.vue
- frontend/src/pages/seeker/auth/SeekerLoginPage.vue
- frontend/src/router/index.js
- frontend/src/stores/UseAuthStore.js
closed: #292 
지원자 로그인 페이지 수정
<br>
1. 헤더컴포넌트 mount시 유저정보 안불러오는 문제 해결
2. 로그아웃시 클라이언트에 저장된 데이터 초기화 
3. 소셜 로그인 수정(닉네임 추가)
4. CSS 스타일링
<br>
> [#292][Feat] 지원자 로그인 페이지 수정

- frontend/src/pages/recruiter/resume/ResumeDetailPage.vue
- frontend/src/pages/recruiter/resume/ResumeListPage.vue
- frontend/src/router/index.js
- frontend/src/stores/UseResumeStore.js
Fixes: #78 
<br>
채용담당자가 등록한 공고 목록에서 공고를 선택하면 해당 공고에 지원한 지원자 목록 조회
<br>
공고 idx로 조회
조회 정보
공고지원서 idx
지원자 이름
서류 합불
지원서 제목
지원 날짜
각 지원자 클릭 시 지원서 상세 페이지로 이동
<br>
<br>
> [#78][Feat] 채용담당자 공고 지원자 관리 페이지 개발 완료

- frontend/src/pages/recruiter/announce/AnnounceDetailPage.vue
- frontend/src/pages/recruiter/announce/AnnounceMainPage.vue
- frontend/src/router/index.js
- frontend/src/stores/UseAnnouncementStore.js
closed #75 
closed #19
<br>
공고 관리 페이지 개발했습니다.
<br>
채용담당자가 공고 메뉴에서 공고 클릭 시 출력되는 전체 공고 리스트 페이지 작업
공고 아이템 클릭시 출력되는 공고 상세페이지 작업
라우팅
<br>
<br>
> [#75][Feat] 채용담당자 공고 관리 페이지 개발

- backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/service/InterviewEvaluateService.java
- backend/src/main/java/com/sabujaks/irs/global/utils/CloudFileUpload.java
closed #296 
<br>
파일, 이미지 업로드 서비스 수정
<br>
1.  컨트롤러에서 파일을 required=false를 해도 필수로 넣어야 하는 문제
2. 업로드 서비스에 null처리 안된거 추가
> [#296][Fix] 파일, 이미지 업로드 서비스 수정

- frontend/src/pages/recruiter/announce/AnnounceRegisterStep1Page.vue
- frontend/src/pages/recruiter/company/CompanyInfoPage.vue
- frontend/src/stores/UseBaseInfoStore.js
- frontend/src/stores/UseCompanyStore.js
- frontend/src/stores/UseCustomFormStore.js
closed #84
<br>
채용담당자 마이페이지에서 보여지는 기업정보 조회 페이지, 기업정보 등록 페이지 개발 
<br>
프론트
기업 관련 페이지 개발
마이페이지 입장 시 이미 등록한 기업이 있다면 조회 화면 보여주기
등록한 기업이 없다면 등록 화면 보여주기
기업인증테이블에서는 등록된 기업 여부와 상관없이 필수 정보를 가져와서 보여준다
기업 이미지 업로드 시 오류가 있는데 이유를 모르겠다. 해결 예정
<br>
> [#84][Feat] 채용담당자 기업 정보 조회 및 등록 페이지 개발

- frontend/src/components/seeker/SeekerHeaderComponent.vue
- frontend/src/components/seeker/SeekerSideBarComponent.vue
#69
<br>
라우팅 수정
<br>
지원자 쪽 헤더와 사이드바 라우팅 약간 수정했습니다.
<br>
> [#69][Fit] seeker 헤더와 사이드바 라우팅 약간 수정

- frontend/src/components/seeker/AwardComponent.vue
- frontend/src/components/seeker/CertificationComponent.vue
- frontend/src/components/seeker/EducationComponent.vue
- frontend/src/components/seeker/InternsActivityComponent.vue
- frontend/src/components/seeker/LanguageComponent.vue
- frontend/src/components/seeker/PersonalHistoryComponent.vue
- frontend/src/components/seeker/PersonalInfoComponent.vue
- frontend/src/components/seeker/PortfolioComponent.vue
- frontend/src/components/seeker/PreferentialEmpComponent.vue
- frontend/src/components/seeker/StudyingAbroadComponent.vue
- frontend/src/components/seeker/TrainingComponent.vue
- frontend/src/pages/recruiter/resume/ResumeDetailPage.vue
- frontend/src/pages/seeker/mypage/MypageIntegrationeResumePage.vue
- frontend/src/pages/seeker/resume/ResumeCreatePage.vue
- frontend/src/pages/seeker/resume/ResumeDetailPage.vue
- frontend/src/pages/seeker/resume/ResumeSubmitPage.vue
- frontend/src/stores/UseResumeStore.js
Fixes: #133 
<br>
지원자가 공고 상세나 마이페이지에서 지원서를 제출 또는 등록할 때 필수 입력값을 체크하고, 입력값에 대한 제한을 두는 로직 추가
<br>
각 항목에 대한 필수값을 입력하지 않으면 alert 창 뜨도록 추가
각 입력값에 제한 추가 (숫자만, 특수기호 제한 등)
<br>
<br>
> [#133][Fix] 지원자 지원서 등록, 제출 페이지 입력값 검증

- frontend/src/pages/recruiter/resume/ResumeDetailPage.vue
- frontend/src/pages/seeker/mypage/MypageIntegrationeResumePage.vue
- frontend/src/pages/seeker/resume/ResumeDetailPage.vue
Fixes: #80 
<br>
지원서 상세 조회 페이지 디자인 수정
<br>
채용담당자 - 지원서 상세조회
지원자 - 통합지원서 상세조회
지원자 - 공고에 제출한 지원서 상세조회
디자인(css) 수정
<br>
<br>
> [#133][Fix] 지원서 상세 조회 페이지 디자인 수정

- backend/src/main/java/com/sabujaks/irs/domain/auth/controller/AuthController.java
- backend/src/main/java/com/sabujaks/irs/domain/auth/model/response/SeekerRes.java
- backend/src/main/java/com/sabujaks/irs/domain/auth/service/AuthService.java
- backend/src/main/java/com/sabujaks/irs/global/config/SecurityConfig.java
Fixes: #21 
<br>
지원자가 지원자의 회원정보 상세 조회
<br>
지원자 idx로 지원자 테이블에서 지원자 정보 조회
이메일, 이름, 닉네임, 성별, 생년월일, 휴대폰번호, 주소, 소셜 타입, 프로필 이미지, 생성 시간, 수정 시간
<br>
<br>
> [#21][Feat] 지원자 회원정보 조회 개발 완료

- frontend/src/pages/seeker/mypage/MypageAnnouceResumePage.vue
- frontend/src/pages/seeker/mypage/MypageIntegrationeResumePage.vue
- frontend/src/pages/seeker/mypage/MypageMainPage.vue
- frontend/src/stores/UseAuthStore.js
- frontend/src/stores/UseResumeStore.js
Fixes: #64 
<br>
지원자가 가입할 때 입력한 회원 정보를 상세 조회
<br>
지원자의 이메일, 이름, 닉네임, 성별, 생년월일, 핸드폰번호, 주소, 소셜 로그인 타입, 프로필사진, 생성날짜, 수정날짜 조회
<br>
<br>
> [#64][Feat] 지원자 회원 정보 조회 페이지 개발 완료

- frontend/src/components/recruiter/InterviewScheduleList.vue
- frontend/src/components/recruiter/InterviewScheduleMain.vue
- frontend/src/components/recruiter/MainSideBarComponent.vue
- frontend/src/pages/recruiter/interview-schedule/InterviewScheduleDetail.vue
- frontend/src/pages/recruiter/interview-schedule/InterviewScheduleMainExp.vue
- frontend/src/pages/recruiter/interview-schedule/InterviewScheduleMainNew.vue
- frontend/src/router/index.js
- frontend/src/stores/UseInterviewScheduleStore.js
- frontend/src/stores/UseMypageNotificationStore.js
closed: #311 
<br>
채용담당자는 서류합격자 지원자들 목록을 조회할 수 있다.
채용담당자는 면접 일정 등록 후 상세 조회 가능하다.
<br>
1. 면접 일정 생성시, 서류 합격자들 목록 조회
2. 면접 일정 등록 후, 상세 조회
> [#311][Feat] 면접 상세조회 & 면접 등록 지원자 조회

- frontend/src/pages/recruiter/interview-schedule/InterviewScheduleDetail.vue
- frontend/src/pages/recruiter/interview-schedule/InterviewScheduleMainExp.vue
- frontend/src/pages/recruiter/interview-schedule/InterviewScheduleMainNew.vue
- frontend/src/pages/recruiter/interview-schedule/ReScheduleMainExp.vue
closed: #313 
<br>
각 면접일정 조회 페이지 여백 삭제 수정
<br>
1. 면접일정 조회 페이지 여백 수정
2. 면접일정 상세조회 페이지 여백 수정
3. 면접일정조율 조회 페이지 여백 수정
> [#313][Feat] container 여백 조절

- backend/src/main/java/com/sabujaks/irs/domain/announcement/repository/AnnouncementRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/company/controller/CompanyController.java
- backend/src/main/java/com/sabujaks/irs/domain/company/service/CompanyService.java
- backend/src/main/java/com/sabujaks/irs/domain/search/controller/SearchController.java
- backend/src/main/java/com/sabujaks/irs/domain/search/service/SearchService.java
#35
<br>
지원자 공고 조회시 필요 기능 수정했습니다.
<br>
백엔드 기업 이미지 조회 메소드 추가
검색 메소드 추가
<br>
> [#35][Fix] 지원자 공고 조회시 필요 기능 코드 수정

- backend/src/main/java/com/sabujaks/irs/domain/alarm/controller/AlarmController.java
- backend/src/main/java/com/sabujaks/irs/domain/auth/repository/EstimatorRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/controller/InterviewScheduleController.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/entity/InterviewParticipate.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/entity/ReSchedule.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/request/InterviewScheduleUpdateReq.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/response/InterviewScheduleRes.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/response/ReScheduleRes.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/repository/InterviewParticipateRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/repository/InterviewScheduleRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/repository/ReScheduleRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/service/InterviewScheduleService.java
- backend/src/main/java/com/sabujaks/irs/domain/video_interview/controller/VideoInterviewController.java
- backend/src/main/java/com/sabujaks/irs/domain/video_interview/model/request/VideoInterviewCreateReq.java
- backend/src/main/java/com/sabujaks/irs/domain/video_interview/model/response/VideoInterviewCreateRes.java
- backend/src/main/java/com/sabujaks/irs/domain/video_interview/service/VideoInterviewService.java
- backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
- backend/src/main/java/com/sabujaks/irs/global/utils/EmailSenderSeeker.java
- backend/src/main/resources/templates/InterviewConfirmOnlineEmail.html
- backend/src/main/resources/templates/InterviewNewEmail.html
- backend/src/main/resources/templates/ResultAcceptEmail.html
- backend/src/main/resources/templates/ResumeRejectEmail.html
#49 
<br>
채용담당자는 면접 일정이 확정되면, 이메일로 알림을 보낼 수 있다.
<br>
1. video-interview service create 로직 수정
2. video-interview controller create 이메일 전송 로직 추가
3. 면접 일정 확정 템플릿 추가
4. 면접 일정 확정 메일 전송 기능 개발
> [#49][Feat] 채용담당자 면접 일정 확정 이메일 전송

- backend/src/main/java/com/sabujaks/irs/global/security/oauth2/OAuth2AuthenticationSuccessHandler.java
closed: #286
<br>
OAuth2 테스트
<br>
OAuth2 테스트 리다이렉트 방식으로 다시변경
> [#286][Feat] k8s OAuth2 test4

- backend/src/main/java/com/sabujaks/irs/domain/search/model/request/FilterDto.java
- backend/src/main/java/com/sabujaks/irs/domain/search/model/request/SearchFilterReq.java
- frontend/src/pages/seeker/announce/AnnounceReadAllPage.vue
- frontend/src/stores/UseAnnouncementStore.js
#69
<br>
지원자 공고 전체 조회 페이지에서 검색 기능 부분 디자인 수정과 스크립트 수정했습니다. 로직 개발중입니다.
<br>
검색 부분 작업
<br>
> [#69][Feat] 지원자 공고 전체 조회 페이지 검색 기능 개발

- backend/src/main/java/com/sabujaks/irs/domain/announcement/model/entity/Announcement.java
- backend/src/main/java/com/sabujaks/irs/domain/auth/model/entity/Seeker.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/model/entity/TotalProcess.java
- backend/src/main/java/com/sabujaks/irs/domain/search/model/request/FilterDto.java
- backend/src/main/java/com/sabujaks/irs/domain/search/model/request/Filterdto.java
#58 
<br>
채용담당자 화상 면접 평가 합불 여부
<br>
1. TotalProcess 엔티티 생성
2. 공고별, 지원자별 서류합격, 1차면접합격, 2차면접합격 여부에 대해 저장
3. 프로젝트 중간에 넣는 부분이므로 기존의 평가 생성 메서드도 같이 수정 진행
> [#58][Feat] 채용담당자 화상 면접 평가 합불 여부 개발

- backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/controller/InterviewEvaluateController.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/model/entity/InterviewEvaluate.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/service/InterviewEvaluateService.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/repository/InterviewScheduleRepository.java
#58 
<br>
채용담당자 화상 면접 평가 합불 여부
<br>
1. TotalProcess 엔티티 생성
2. 공고별, 지원자별 서류합격, 1차면접합격, 2차면접합격 여부에 대해 저장
3. 프로젝트 중간에 넣는 부분이므로 기존의 평가 생성 메서드도 같이 수정 진행
> [Feat] 채용담당자 화상 면접 평가 합불 여부 개발

- frontend/src/pages/seeker/announce/AnnounceReadAllPage.vue
- frontend/src/pages/seeker/resume/ResumeCreatePage.vue
- frontend/src/pages/seeker/resume/ResumeSubmitPage.vue
- frontend/src/stores/UseAnnouncementStore.js
#69
<br>
지원자 공고 전체 조회 페이지 개발
검색기능 추가
<br>
채용형태(신입, 경력), 모집직무(공고 등록시 선택했던 카테고리), 근무지역(서울 등)으로 검색 가능
단, 키워드로 검색창에 검색하고 싶을 때는 선택했던 필터 초기화 필수
마지막으로, 하나의 필터카테고리당 하나의 필터만 추가해야 함. 2개 이상일 시, 마지막 필터가 적용됨.
<br>
> [#69][Feat] 지원자 공고 전체조회 페이지 및 검색기능 개발

- backend/src/main/java/com/sabujaks/irs/global/config/Bean.java
- backend/src/main/java/com/sabujaks/irs/global/config/RemoveJSESSIONID.java
closed: #337
<br>
JSESSIONID 삭제 설정 추가
<br>
1.  JSESSIONID 삭제 설정 추가 RemoveJSESSIONID
<br>
> [#337][Feat] JSESSIONID 삭제 설정 추가 완료

- backend/src/main/java/com/sabujaks/irs/domain/video_interview/service/VideoInterviewService.java
- backend/src/main/java/com/sabujaks/irs/global/config/SecurityConfig.java
closed: #346 
<br>
지원자&면접진 화상 면접방 참여시 인증 방식을 수정
<br>
<br>
> [#346][Feat] 지원자 & 면접진 화상 면접방 시간대 접근 제어 수정 

- backend/src/main/java/com/sabujaks/irs/domain/alarm/model/entity/Alarm.java
- backend/src/main/java/com/sabujaks/irs/domain/alarm/service/AlarmService.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/service/InterviewScheduleService.java
- backend/src/main/java/com/sabujaks/irs/domain/total_process/repository/TotalProcessRepository.java
- backend/src/main/java/com/sabujaks/irs/global/utils/EmailSenderSeeker.java
- backend/src/main/resources/templates/InterviewExpEmail.html
#348  
<br>
비동기 Email 전송 로직에 Alarm 저장 로직 추가했습니다.
기존 Alarm 저장 로직 삭제했습니다.
<br>
- Alarm Entity에서 미사용 url 칼럼 삭제
- 기존 Alarm 저장 로직 삭제
- Alarm 저장 로직 Email 전송 로직 안에 추가
<br>
> [#348][Feat] Email 전송 & Alarm 저장 로직 변경

- frontend/src/assets/css/grid.css
- frontend/src/components/recruiter/ReScheduleDetail.vue
- frontend/src/components/seeker/SeekerHeaderComponent.vue
- frontend/src/pages/recruiter/interview-schedule/InterviewScheduleMainExp.vue
- frontend/src/pages/recruiter/interview-schedule/ReScheduleMainExp.vue
- frontend/src/pages/seeker/mypage/MypageNotificationPage.vue
#350 
<br>
면접 일정 조율 페이지에 인터뷰 차수 checkbox 추가했습니다.
변경을 하는 날짜에 대해서도 시간대 필터링 추가했습니다.
<br>
- 면접 일정 조율 페이지 인터뷰 차수 추가
- 변경 날짜 시간대 필터링 추가
<br>
> [#350][Fix] 면접 일정 조율 페이지 인터뷰 차수 & 시간대 필터링 추가

- frontend/src/pages/recruiter/resume/ResumeListPage.vue
- frontend/src/pages/seeker/mypage/MypageAnnouceResumePage.vue
- frontend/src/pages/seeker/mypage/MypageIntegrationeResumePage.vue
- frontend/src/pages/seeker/mypage/MypageMainPage.vue
- frontend/src/pages/seeker/resume/ResumeCreatePage.vue
- frontend/src/pages/seeker/resume/ResumeDetailPage.vue
- frontend/src/stores/UseResumeStore.js
Fixes: #65 
<br>
지원자가 본인이 지원한 공고, 지원 정보 목록을 조회
<br>
상태 값을 공고 진행중 or 마감에서 서류, 1차면접, 2차면접, 최종 합불로 조회가능하게 수정
<br>
<br>
> [#65][Fix] totalProcess 채용 진행 결과 조회할 수 있게 수정

- frontend/src/pages/seeker/announce/AnnounceDetailPage.vue
- frontend/src/pages/seeker/announce/AnnounceReadAllPage.vue
closed #69
<br>
검색기능 스크립트 오류 해결, 정렬기능 추가
<br>
프론트
공고 전체 조회 페이지에서 검색 스크립트 수정
하나의 공고 아이템에 커서 호버 시 나오는 정보 추가 ( 기업소개, 마감날, 채용형태, 모집직무)
.bg 이미지 반응형 설정하기위해 넒이 부모 100%로 수정했는데 다른부분이 이상하여 다시 복구
[정렬 추가] 전체, 최신 등록순, 마감 임박순, 마감된 공고 제외순
- 정렬은 필터와 키워드 검색으로 인해 나온 결과에서도 적용됩니다.
- 검색 또는 필터링 결과가 반환된 후 initialAnnouncements에 현재 데이터를 저장 -> 정렬이나 다른 기능을 위해 검색 결과를 유지 가능
<br>
> [#69][Fix] 지원자 공고 전체조회 페이지 검색기능 수정, 정렬기능 추가

- backend/src/main/java/com/sabujaks/irs/domain/video_interview/model/response/VideoInterviewCreateRes.java
- backend/src/main/java/com/sabujaks/irs/domain/video_interview/service/VideoInterviewService.java
- backend/src/main/java/com/sabujaks/irs/global/utils/EmailSenderSeeker.java
- backend/src/main/resources/templates/InterviewConfirmOnlineEmail.html
- backend/src/main/resources/templates/InterviewExpEmail.html
- backend/src/main/resources/templates/InterviewNewEmail.html
closed #355 
<br>
VideoInterviewCreateReq에 공고 idx 추가했습니다.
면접확정이메일 템플릿 및 로직 완성했습니다.
<br>
- VideoInterviewCreateReq announcementIdx 추가
- 면접확정 이메일 템플릿 완성
- 면접확정 이메일 로직 완성
<br>
> [#355][Feat] 면접 확정 메일(경력, 신입) 템플릿 완성

- backend/src/main/java/com/sabujaks/irs/domain/announcement/service/AnnouncementService.java
- backend/src/main/java/com/sabujaks/irs/domain/search/service/SearchService.java
#339
<br>
공고 조회 코드 수정
<br>
하나의 공고 조회 시 기업 레포지토리를 두번 조회하는 부분 한번으로 수정
<br>
> [#339][Fix] 공고조회 코드 수정

- backend/src/main/java/com/sabujaks/irs/domain/auth/service/EmailVerifyService.java
#97
<br>
회원가입 시 이메일 인증 url 수정
<br>
localhost로 갔던 이메일 인증 url
-> "https://www.sabujaks-irs.kro.kr/api/api/auth/email-verify?email="
<br>
> [#97][Fix] 이메일 검증 코드 url 수정

- backend/src/main/java/com/sabujaks/irs/domain/video_interview/service/VideoInterviewService.java
- backend/src/main/java/com/sabujaks/irs/global/security/CustomUserDetails.java
- backend/src/main/java/com/sabujaks/irs/global/security/exception/CustomAccessDeniedHandler.java
- backend/src/main/java/com/sabujaks/irs/global/security/exception/CustomLoginFailureHandler.java
- backend/src/main/java/com/sabujaks/irs/global/security/filter/JwtFilter.java
- backend/src/main/java/com/sabujaks/irs/global/security/filter/LoginFilter.java
- backend/src/main/java/com/sabujaks/irs/global/security/oauth2/CustomOAuth2UserDetails.java
- backend/src/main/java/com/sabujaks/irs/global/security/oauth2/CustomOAuth2UserService.java
- backend/src/main/java/com/sabujaks/irs/global/security/oauth2/OAuth2AuthenticationSuccessHandler.java
closed: #359 
<br>
지원자 소셜로그인시 VITOKEN 설정 추가
<br>
1. 면접 권한(VITOKEN) 발급
2. VITOKEN 조회해서 권한 저장
3. 시큐리티 설정 수정
> [#359][Fix] 지원자 소셜 로그인 수정

- frontend/src/pages/seeker/auth/SeekerLoginPage.vue
closed: #286
<br>
OAuth2 테스트
<br>
프론트엔드 요청 URL 변경
> [#286][Feat] k8s OAuth2 test5

- backend/src/main/java/com/sabujaks/irs/domain/total_process/controller/TotalProcessController.java
#231
<br>
젠킨스 빌드 테스트
<br>
배포디비 재생성
<br>
<br>
> [Feat] jenkins back test

- frontend/src/pages/seeker/auth/SeekerLoginPage.vue
closed: #286
<br>
OAuth2 테스트
<br>
프론트엔드 요청 URL 변경
> [#286][Feat] k8s OAuth2 test6

- backend/src/main/resources/application.yml
closed: #286
<br>
OAuth2 테스트
<br>
application.yml google 리다이렉션 URL 추가
> [#286][Feat] k8s OAuth2 test7

- frontend/src/pages/seeker/resume/ResumeSubmitPage.vue
Fixes: #80 
<br>
지원서 상세 조회 페이지 디자인 수정
<br>
채용담당자 - 지원서 상세조회
지원자 - 통합지원서 상세조회
지원자 - 공고에 제출한 지원서 상세조회
디자인(css) 수정
<br>
<br>
> [#80][Fix] 지원자 지원서 상세조회 페이지 수정

- frontend/src/pages/recruiter/auth/RecruiterSignupPage.vue
closed: #364 
<br>
채용담당자 회원가입 페이지 수정 완료
<br>
1. validation 수정
> [#364][Fix] 채용담당자 회원가입 페이지 수정 완료

- frontend/src/pages/recruiter/interview-schedule/InterviewScheduleMainNew.vue
시연 영상 찍는 중에 시간 수정이 필요하여 수정했습니다.
> [Fix] 면접시간 수정

- backend/src/main/java/com/sabujaks/irs/domain/video_interview/service/VideoInterviewService.java
> [Fix] 화상면접방 시간대 접근제어 수정 완료

- frontend/src/pages/seeker/auth/SeekerSignupPage.vue
> [Fix] 회원가입 요청값 추가

- frontend/src/pages/video-interview/VideoInterviewRoomPage.vue
openvidu 관련 new 할떄 url 추가 ('https://openvidu-svc:4443');
> [Fix] openvidu url 추가 수정

- frontend/src/pages/video-interview/VideoInterviewRoomPage.vue
openvidu url 추가 수정 https -> http
> [Fix] openvidu 추가 수정

- frontend/src/pages/video-interview/VideoInterviewRoomPage.vue
openvidu 추가 수정2 
session.value = OV.value.initSession();
OV.value.setWsServerUrl('wss://openvidu-svc:4443');
> [Fix] openvidu 추가 수정2

- frontend/src/pages/video-interview/VideoInterviewRoomPage.vue
> [Fix] openvidu 추가 수정3

- frontend/src/pages/video-interview/VideoInterviewRoomPage.vue
OV.value.setWsServerUrl('wss://sabujaks-irs.kro.kr/openvidu'); 로 변경
> [Fix] openvidu 추가 수정4

- frontend/src/assets/css/grid.css
- frontend/src/components/recruiter/InterviewScheduleList.vue
- frontend/src/pages/recruiter/interview-schedule/InterviewScheduleMainExp.vue
- frontend/src/pages/recruiter/resume/ResumeListPage.vue
- frontend/src/stores/UseInterviewScheduleStore.js
- frontend/src/stores/UseResumeStore.js
closed #391 
<br>
채용담당자는 각 채용 프로세스 결과를 일괄전송 버튼 하나로, 지원자에게 일괄 전송할 수 있습니다.
채용담당자는 화상 면접방 일괄생성 버튼을 통해, 일괄생성할 수 있습니다.
<br>
- 각 프로세스 결과 일괄 전송 버튼 기능 개발
- 화상 면접 방 일괄 생성 버튼 기능 개발
<br>
> [#391][Feat] 프로세스 결과 일괄 전송 & 면접방 일괄 생성 버튼

- backend/src/main/java/com/sabujaks/irs/domain/video_interview/controller/VideoInterviewController.java
- backend/src/main/java/com/sabujaks/irs/domain/video_interview/service/VideoInterviewService.java
#396
<br>
동적스케줄링 json 에러 제거했습니다.
<br>
- 동적생성 로직 부분 에러 제거
<br>
> [#396][Hotfix] 동적스케줄링 json Error

- frontend/src/components/seeker/SeekerHeaderComponent.vue
- frontend/src/components/seeker/SeekerSideBarComponent.vue
- frontend/src/pages/seeker/announce/AnnounceDetailPage.vue
- frontend/src/pages/seeker/mypage/MypageAnnouceResumePage.vue
- frontend/src/pages/seeker/mypage/MypageIntegrationeResumePage.vue
- frontend/src/pages/seeker/mypage/MypageMainPage.vue
- frontend/src/pages/seeker/mypage/MypageNotificationPage.vue
- frontend/src/pages/seeker/resume/ResumeDetailPage.vue
#404
<br>
지원자 마이페이지와 헤더, 사이드바도 함께 수정했습니다.
공고 상세 페이지 수정도 약간 있어서 같이 올립니다.
<br>
공통 : 미구현 버튼 주석처리, 배경색 화이트 변경
지원자 사이드바
-일정관리 메뉴 삭제
지원자 헤더
-공고달력, 알림 메뉴 삭제
<br>
> [#404][Refactor] 지원자 마이페이지 및 헤더 디자인 개선

- backend/src/main/java/com/sabujaks/irs/domain/announcement/controller/AnnouncementController.java
- backend/src/main/java/com/sabujaks/irs/domain/announcement/model/response/AnnouncementReadDetailRes.java
- backend/src/main/java/com/sabujaks/irs/domain/announcement/service/AnnouncementService.java
- backend/src/main/java/com/sabujaks/irs/domain/auth/controller/AuthController.java
- backend/src/main/java/com/sabujaks/irs/domain/auth/model/response/RecruiterInfoReadRes.java
- backend/src/main/java/com/sabujaks/irs/domain/auth/service/AuthService.java
- backend/src/main/java/com/sabujaks/irs/domain/company/controller/CompanyController.java
- backend/src/main/java/com/sabujaks/irs/domain/company/model/response/BenefitCategory.java
- backend/src/main/java/com/sabujaks/irs/domain/company/model/response/CompanyInfoReadRes.java
- backend/src/main/java/com/sabujaks/irs/domain/company/model/response/CompanyReadRes.java
- backend/src/main/java/com/sabujaks/irs/domain/company/service/CompanyService.java
- frontend/src/stores/UseAnnouncementStore.js
closed #410
<br>
공고 패키지에 있던 메서드와 리스폰스 이동
<br>
announcement 패키지에서 company, auth 패키지로 각 메서드 이동
-기업 복리후생 조회 메서드, BenefitCategory, CompanyInfoReadRes 리스폰스
-채용담당자 일부정보 조회 메서드, RecruiterInfoReadRes 리스폰스
<br>
> [#410][Refactor] 공고 패키지 메서드 및 응답 위치 변경

- frontend/src/pages/recruiter/announce/AnnounceMainPage.vue
- frontend/src/pages/recruiter/announce/AnnounceRegisterStep1Page.vue
- frontend/src/pages/recruiter/announce/AnnounceRegisterStep2Page.vue
- frontend/src/pages/recruiter/company/CompanyInfoPage.vue
- frontend/src/pages/seeker/announce/AnnounceDetailPage.vue
- frontend/src/pages/seeker/announce/AnnounceReadAllPage.vue
#413
<br>
공고 관련 페이지 디자인 개선
<br>
채용담당자 공고 관리 페이지 디자인 개선
지원서 폼 등록 페이지 디자인 개선
버튼과 input -> textarea 변경
<br>
> [#413][Refactor] 공고 관리 및 등록 페이지 디자인 개선

- backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
closed #420
<br>
Interview 전체 BaseResponseMessage Code 수정했습니다.
<br>
- Interview 전체 8000번대로 수정
<br>
> [#420][Refactor] BaseResponseMessage Code 정리

- backend/src/main/java/com/sabujaks/irs/domain/resume/controller/ResumeController.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/repository/ResumeRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/service/ResumeService.java
#424
<br>
채용담당자 공고에 지원한 지원자 목록 페이징 처리
<br>
<br>
> [#424][Refactor] 채용담당자 지원자 목록 페이징 처리

- frontend/src/pages/recruiter/resume/ResumeListPage.vue
- frontend/src/stores/UseResumeStore.js
#426 
<br>
채용담당자 공고에 지원한 지원자 목록 페이징 처리
<br>
<br>
> [#426][Refactor] 채용담당자 지원자 목록 페이징 처리

- backend/src/main/java/com/sabujaks/irs/domain/video_interview/controller/VideoInterviewController.java
- backend/src/main/java/com/sabujaks/irs/domain/video_interview/model/entity/VideoInterview.java
- backend/src/main/java/com/sabujaks/irs/domain/video_interview/model/response/VideoInterviewReadRes.java
- backend/src/main/java/com/sabujaks/irs/domain/video_interview/service/VideoInterviewService.java
- frontend/src/pages/video-interview/VideoInterviewMainPage.vue
- frontend/src/pages/video-interview/VideoInterviewRoomPage.vue
closed #431 
<br>
화상 면접방 목록 조회 개선
<br>
<br>
> [#431][Refactor] 화상 면접방 목록 조회 개선

- backend/src/main/java/com/sabujaks/irs/domain/announcement/controller/AnnouncementController.java
- backend/src/main/java/com/sabujaks/irs/domain/announcement/repository/AnnouncementRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/announcement/service/AnnouncementService.java
closed: #423
<br>
채용담당자 공고에 지원한 지원자 목록 페이징 처리
채용담당자가 등록한 공고 목록 페이징 처리
<br>
<br>
> [#423][Refactor] 채용담당자 공고 목록 페이징 처리

- frontend/src/pages/recruiter/announce/AnnounceMainPage.vue
- frontend/src/pages/recruiter/resume/ResumeMainPage.vue
- frontend/src/stores/UseAnnouncementStore.js
#413 
<br>
채용담당자가 등록한 공고 목록 페이징 처리
<br>
<br>
> [#413][Refactor] 채용담당자 공고 관리 페이지 공고 목록 페이징 처리

- backend/src/main/java/com/sabujaks/irs/domain/video_interview/model/response/VideoInterviewReadRes.java
- backend/src/main/java/com/sabujaks/irs/domain/video_interview/service/VideoInterviewService.java
- frontend/src/pages/video-interview/VideoInterviewMainPage.vue
- frontend/src/router/index.js
- frontend/src/stores/UseVideoInterviewStore.js
#430 
<br>
화상 면접방 목록 페이지 개선
<br>
1. 화상면접대기방 uuid 삭제
2. 공고명 추가
3. 변수명, 메소드명 수정(announceUUID -> announcementUUID)
4. 디자인 수정, 리팩토링
5. 페이지네이션 x
> [#430][Refactor] 화상 면접방 목록 페이지 개선

- backend/src/main/java/com/sabujaks/irs/domain/resume/controller/ResumeController.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/repository/ResumeRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/service/ResumeService.java
closed: #424 
<br>
지원자 공고별 지원 목록 페이징 처리
<br>
<br>
> [#424][Refactor] 지원자 공고별 지원 목록 페이징 처리

- frontend/src/components/seeker/SeekerHeaderComponent.vue
- frontend/src/pages/recruiter/auth/RecruiterLoginPage.vue
- frontend/src/pages/recruiter/auth/RecruiterSignupPage.vue
- frontend/src/pages/seeker/auth/SeekerLoginPage.vue
- frontend/src/pages/seeker/auth/SeekerSignupPage.vue
closed #446 
<br>
회원가입, 로그인 페이지 개선
<br>
1. 비밀번호 처리
2. 휴대폰번호 형식 01012341234
3. 소셜로그인이 완료되지 않았는데 isLoggedinTrue 되는 문제
4. 소셜로그인시 토스트 메시지 2개 뜨는 오류
5. 소셜로그인 버튼 이미지 링크 수정
6. CSS 수정
> [#446][Refactor] 회원가입, 로그인 페이지 개선

- frontend/src/pages/recruiter/announce/AnnounceRegisterStep1Page.vue
- frontend/src/pages/recruiter/company/CompanyInfoPage.vue
- frontend/src/stores/UseAnnouncementStore.js
- frontend/src/stores/UseCompanyStore.js
closed #432
<br>
기업 관리 페이지 개선했습니다.
<br>
기업정보 없을 때 공고 등록할려하면 알림창 후 기업정보 등록으로 리다이렉트
기업 구분 - SELECTBOX
매출액 - 숫자만
복리후생 배경색, 버튼 디자인 변경
등록하기 버튼 밑 여백 및 위치 조정
등록 후 현재 페이지 리다이렉트 처리 → 기업 정보 조회로 출력됨
<br>
> [#432][Refactor] 기업 정보 등록, 조회 페이지 개선

- frontend/src/components/seeker/SeekerSideBarComponent.vue
- frontend/src/pages/seeker/mypage/MypageAnnouceResumePage.vue
- frontend/src/pages/seeker/mypage/MypageIntegrationeResumePage.vue
- frontend/src/pages/seeker/mypage/MypageMainPage.vue
- frontend/src/stores/UseResumeStore.js
#427 
<br>
지원자 마이페이지 개선
<br>
통합지원서 관리 페이지 사이드바 사이즈 조정
마이페이지 사이드바에 지원서 등록 삭제
통합지원서 관리 페이지 진입 시 통합지원서 등록 여부 조회 후 통합지원서 등록 페이지나 조회 페이지로 리다이렉트
마이페이지 메인 css 변경
공고별 지원서 관리 css 변경
alert -> toast
<br>
> [#427][Refactor] 지원자 마이페이지 개선

- backend/src/main/java/com/sabujaks/irs/domain/announcement/model/entity/Announcement.java
- backend/src/main/java/com/sabujaks/irs/domain/announcement/service/AnnouncementService.java
- backend/src/main/java/com/sabujaks/irs/global/config/SecurityConfig.java
#451
<br>
공고 등록 로직 개선
<br>
근무지역 컬럼 길이 늘리기 region (현재 20), 다른 컬럼도 추가로 늘림
이미지 업로드일 때 카테고리 db에 들어가게 수정
공고 생성 시 채용담당자 토큰없을때 null 오류 시큐리티 설정에 추가
<br>
> [#451][Refactor] 공고 등록 필드 추가 및 시큐리티 설정

- frontend/src/assets/css/grid.css
- frontend/src/pages/seeker/mypage/MypageMainPage.vue
- frontend/src/pages/seeker/mypage/MypageNotificationPage.vue
#427 
<br>
지원자 마이페이지 개선
<br>
- 마이페이지 디자인 개선
- 알림페이지 margin 추가된 부분 삭제
<br>
> [#427][Refactor] 지원자 마이페이지 및 알림 디자인 개선

- backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/model/response/InterviewEvaluateReadResumeInfoRes.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/service/InterviewEvaluateService.java
- frontend/src/components/seeker/SeekerHeaderComponent.vue
- frontend/src/components/video-interview/UserVideo.vue
- frontend/src/components/video-interview/VideoInterviewResumeComponent.vue
- frontend/src/pages/video-interview/VideoInterviewMainPage.vue
- frontend/src/pages/video-interview/VideoInterviewRoomPage.vue
closed: #455 
<br>
화상 면접방 페이지 개선
<br>
1. 지원서보기
2. 면접관이 지원자 음소거 할 수 있게 수정 필요 (현재는 지원자가 면접관 음소거 가능)
3. 면접관에서 면접관의 이름을 출력하게 수정
4. css 디자인 수정
<br>
> [#455][Refactor] 화상 면접방 페이지 개선

- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/service/InterviewScheduleService.java
- frontend/src/pages/recruiter/auth/RecruiterLoginPage.vue
- frontend/src/pages/recruiter/interview-evaluate/InterveiwEvaluateResultDetailPage.vue
- frontend/src/pages/recruiter/interview-evaluate/InterviewEvaluateFormCreatePage.vue
- frontend/src/pages/recruiter/interview-evaluate/InterviewEvaluateResultPage.vue
- frontend/src/pages/recruiter/interview-schedule/InterviewScheduleDetail.vue
- frontend/src/pages/recruiter/interview-schedule/InterviewScheduleListPage.vue
- frontend/src/pages/recruiter/resume/ResumeMainPage.vue
#462 
<br>
채용담당자 인터뷰 일정 생성 페이지 개선
<br>
- 전역 style scoped 설정 -> 스타일 충돌 해결
- 면접관 이메일만 입력 -> 이름-이메일 입력
<br>
> [#462][Refactor] 채용담당자 인터뷰 일정 생성 페이지 개선

- backend/src/main/java/com/sabujaks/irs/domain/auth/model/entity/Estimator.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/model/response/InterviewEvaluateReadRes.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/service/InterviewEvaluateService.java
- backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/service/InterviewScheduleService.java
- backend/src/main/java/com/sabujaks/irs/global/utils/email/service/EmailSenderSeeker.java
- frontend/src/pages/recruiter/auth/RecruiterSignupPage.vue
- frontend/src/pages/recruiter/interview-evaluate/InterveiwEvaluateResultDetailPage.vue
- frontend/src/pages/recruiter/interview-evaluate/InterviewEvaluateFormCreatePage.vue
- frontend/src/pages/recruiter/interview-evaluate/InterviewEvaluateResultPage.vue
- frontend/src/pages/seeker/auth/SeekerSignupPage.vue
- frontend/src/pages/video-interview/VideoInterviewRoomPage.vue
closed: #469 
<br>
채용담당자 인터뷰 평가 페이지 개선
<br>
1. 면접 평가표 조회 기능 수정에 따른 CSS 수정
<br>
> [#469][Refactor] 채용담당자 인터뷰 평가 페이지 개선

- frontend/src/components/seeker/PersonalInfoComponent.vue
- frontend/src/pages/seeker/mypage/MypageAnnouceResumePage.vue
- frontend/src/pages/seeker/mypage/MypageMainPage.vue
- frontend/src/pages/seeker/mypage/MypageNotificationPage.vue
- frontend/src/pages/seeker/resume/ResumeCreatePage.vue
- frontend/src/pages/seeker/resume/ResumeDetailPage.vue
- frontend/src/pages/seeker/resume/ResumeSubmitPage.vue
- frontend/src/stores/UseResumeStore.js
#427 
<br>
지원자 지원서 관련 페이지 개선
<br>
지원서 등록 페이지 css 변경
지원서 제출 페이지 css 변경
alert -> toast
지원서 제출 페이지 인적사항 성별 기본값 추가
지원서 등록, 제출 페이지 인적사항 주소 설명 추가
지원서 등록, 제출 페이지 인적사항 이메일 부분에 가입한 이메일을 고정값으로 수정
지원서 제출 페이지 자기소개서 추가 및 삭제 못하게 수정
지원서 등록, 제출 페이지 사이드바 위치 조정
<br>
> [#411][Refactor] 지원자 지원서 페이지 개선

- frontend/src/components/recruiter/MainSideBarComponent.vue
- frontend/src/pages/recruiter/announce/AnnounceMainPage.vue
- frontend/src/pages/recruiter/resume/ResumeDetailPage.vue
- frontend/src/pages/recruiter/resume/ResumeListPage.vue
- frontend/src/pages/recruiter/resume/ResumeMainPage.vue
- frontend/src/stores/UseResumeStore.js
#426 
<br>
채용담당자 지원서 관리 페이지 개선
<br>
페이징 처리 디자인 변경
관련 페이지 css 수정
<br>
> [#426][Refactor] 채용담당자 지원서 관리 페이지 개선

- backend/src/main/java/com/sabujaks/irs/domain/resume/service/ResumeService.java
closed: #479 
<br>
지원서 제출 페이지 진입 시 필요한 정보 조회 기능 개선
<br>
지원자가 해당 공고에 지원했을 때 예외처리 추가
<br>
> [#479][Refactor] 지원서 제출 페이지 진입 시 필요한 정보 조회 개선

- frontend/src/pages/seeker/resume/ResumeSubmitPage.vue
- frontend/src/stores/UseResumeStore.js
#411 
<br>
지원자 지원서 제출 페이지 개선
<br>
리다이렉트 처리
<br>
> [#411][Refactor] 지원자 지원서 제출 페이지 개선

- frontend/src/pages/seeker/announce/AnnounceReadAllPage.vue
#481
<br>
검색 필터 오류 해결
<br>
모집직무를 카테고리 코드가 들어가도록 변경했기 때문에 필터도 description이 아니라 code값을 넘겨주도록 변경
필터 x 클릭 시 드롭다운에 반영 안되는 오류 수정
필터 값 안들어가는 오류 수정
<br>
> [#481][Refactor] 지원자 메인페이지 필터 개선

- backend/src/main/java/com/sabujaks/irs/domain/system/controller/HealthController.java
closed: #231 
<br>
k8s db test
<br>
db 초기화
> [Feat] k8s test

- backend/src/main/java/com/sabujaks/irs/domain/auth/service/EmailVerifyService.java
- backend/src/main/java/com/sabujaks/irs/global/utils/email/service/EmailSenderSeeker.java
- backend/src/main/resources/templates/SignupEmail.html
closed #493 
<br>
회원가입 진행시 이메일 인증 템플릿 추가
<br>
- 기존 email 전송 로직 emailSenderSeeker로 통합
- 이메일 인증 템플릿 추가
<br>
> [#493][Refactor] 회원가입 이메일 인증 템플릿 추가

- frontend/src/pages/recruiter/company/CompanyInfoPage.vue
- frontend/src/pages/seeker/announce/AnnounceDetailPage.vue
- frontend/src/pages/seeker/announce/AnnounceReadAllPage.vue
#481
<br>
공고 상세 보기 페이지에서 기업 이미지 관련 개선, 지원 마감시 버튼 이벤트 개선
<br>
공고 전체 조회 메인페이지에 각 공고마다 기업대표 이미지 출력 변경
공고 상세 조회에 기업 이미지 작게 나오게 추가
지원기간이 마감되었을 때 버튼 이벤트 x, 버튼 '즉시 지원' -> '지원 마감'
<br>
> [#481][Refactor] 지원자 메인페이지 공고 관련 전체 개선

- backend/src/main/java/com/sabujaks/irs/domain/announcement/model/response/AnnouncementReadAllRes.java
- backend/src/main/java/com/sabujaks/irs/domain/announcement/model/response/AnnouncementReadDetailRes.java
- backend/src/main/java/com/sabujaks/irs/domain/announcement/service/AnnouncementService.java
#481
<br>
공고 전체 조회시 로직 변경
<br>
공고 전체 조회시 기업이미지 url 리스트 res 추가
<br>
> [#481][Refactor] 공고 전체조회 기업이미지 부분 로직 개선

- backend/src/main/java/com/sabujaks/irs/domain/auth/controller/AuthController.java
- backend/src/main/java/com/sabujaks/irs/global/utils/email/service/EmailSenderSeeker.java
- backend/src/main/resources/templates/SignupEmail.html
closed #493 
<br>
이메일 인증시, redirect url 수정
<br>
- redirect url 수정
<br>
> [#493][Refactor] 회원가입 이메일 인증 redirect url 수정

- backend/src/main/java/com/sabujaks/irs/domain/announcement/repository/AnnouncementRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/search/service/SearchService.java
#481
<br>
키워드 검색 쿼리 변경
<br>
메인페이지에서 키워드 검색 시 기존 공고 타이틀과 모집분야 + 기업이름 까지 추가함
<br>
> [#481][Refactor] 키워드 검색 기업이름 포함 쿼리 개선

- frontend/src/pages/recruiter/announce/AnnounceRegisterStep1Page.vue
- frontend/src/pages/seeker/announce/AnnounceReadAllPage.vue
#481
<br>
지원자 메인페이지 검색창 및 공고등록 페이지 개선
<br>
키워드 검색 창에 기업명 포함 검색으로 안내문구 수정
공고등록 페이지에 상시모집 드롭다운 삭제
<br>
> [#481][Refactor] 지원자 메인페이지 검색창 및 공고등록 페이지 개선

- backend/build.gradle
- backend/src/main/java/com/sabujaks/irs/domain/announcement/service/AnnouncementService.java
- backend/src/main/java/com/sabujaks/irs/domain/resume/service/ResumeService.java
- backend/src/main/java/com/sabujaks/irs/global/common/aspect/ExecutionTimeAspect.java
- backend/src/main/java/com/sabujaks/irs/global/config/FreeMarkerConfig.java
- backend/src/main/java/com/sabujaks/irs/global/config/RedisConfig.java
- backend/src/main/resources/application.yml
closed: #515 
<br>
메소드 실행시간 측정을 위한 Aspect 클래스 작성
<br>
메소드 실행시간 측정을 위한 Aspect 클래스 추가
공고 전체 조회, 공고에 지원한 지원서 상세 조회 메소드 시간 측정 어노테이션 추가
> [Feat] 메소드 실행시간 측정을 위한 Aspect 클래스 작성

- backend/src/main/resources/application.yml
closed: #515
<br>
레디스 설정
<br>
yml 파일에 REDIS_PW 추가
> [#515][Feat] 레디스 비밀번호 설정 추가

- backend/src/main/java/com/sabujaks/irs/domain/announcement/repository/querydsl/AnnouncementDslRepositoryImpl.java
- backend/src/main/java/com/sabujaks/irs/domain/search/controller/SearchController.java
closed: #519  
<br>
검색 기능 수정
<br>
검색 GET으로 수정
<br>
> [#519][Refactor] 공고 검색 기능 수정

- frontend/src/pages/seeker/announce/AnnounceReadAllPage.vue
- frontend/src/stores/UseAnnouncementStore.js
closed: #520 
<br>
검색 기능 수정
기존에 메인 페이지에서 공고 전체 조회, 필터 검색, 키워드 검색 3개를 사용하고 있었는데 나누어져 있을 때 페이징 처리가 어려운 점을 고려해 1개의 api로 합쳤습니다.
<br>
페이징 처리
메인 페이지 조회 api를 검색 api 하나로 사용하게 수정
<br>
> [#520][Refactor] 메인 페이지 조회 및 검색 기능 수정과 페이징 처리

- frontend/src/pages/seeker/announce/AnnounceReadAllPage.vue
- frontend/src/pages/seeker/auth/SeekerLoginPage.vue
closed: #520 
<br>
메인 페이지 디자인 수정 및 네이버 로그인 삭제
<br>
페이징 처리 디자인 변경
네이버 로그인 삭제
<br>
> [#520][Refactor] 메인 페이지 페이징 디자인 변경 및 네이버 로그인 삭제

- backend/src/main/java/com/sabujaks/irs/domain/search/service/SearchService.java
closed: #519  
<br>
검색 메소드에 실행시간 측정 어노테이션 추가
<br>
검색 메소드에 실행시간 측정 어노테이션 추가 (@ExeTimer)
<br>
> [#519][Refactor] 검색 메소드에 실행시간 측정 어노테이션 추가

- frontend/src/components/recruiter/MainSideBarComponent.vue
- frontend/src/pages/recruiter/total-process/TotalProcessListPage.vue
- frontend/src/pages/recruiter/total-process/TotalProcessMainPage.vue
- frontend/src/router/index.js
- frontend/src/stores/UseTotalProcessStore.js
closed #529 
<br>
채용담당자가 각 공고별, 지원자 채용 프로세스 결과를 확인할 수 있다.
<br>
- 채용담당자 페이지 사이드바 메뉴 추가
- 채용담당자 채용결과 페이지 추가
<br>
> [#529][Feat] 채용담당자 채용 프로세스 결과 확인

- backend/src/main/java/com/sabujaks/irs/domain/total_process/controller/TotalProcessController.java
- backend/src/main/java/com/sabujaks/irs/domain/total_process/model/response/TotalProcessReadAllRes.java
- backend/src/main/java/com/sabujaks/irs/domain/total_process/repository/TotalProcessRepository.java
- backend/src/main/java/com/sabujaks/irs/domain/total_process/service/TotalProcessService.java
- backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
closed #531 
<br>
채용담당자가 각 공고별, 지원자 채용 프로세스 결과를 확인할 수 있다.
<br>
- total-process controller 추가
- total-process service 추가
- total-process repository 추가
- total-process response dto 추가
<br>
> [#531][Feat] 채용담당자 공고별, 지원자별 채용 프로세스 결과 확인

- frontend/src/components/recruiter/MainSideBarComponent.vue
- frontend/src/pages/recruiter/announce/AnnounceDetailPage.vue
- frontend/src/pages/recruiter/announce/AnnounceRegisterStep1Page.vue
- frontend/src/pages/recruiter/interview-schedule/InterviewScheduleListPage.vue
- frontend/src/pages/seeker/announce/AnnounceDetailPage.vue
- frontend/src/stores/UseAnnouncementStore.js
closed #535
<br>
채용절차 개선
<br>
공고 등록 step1 페이지 채용절차 날짜 선택 부분 추가 - 서류전형, 전체전형
공고 상세조회 (채용담당자편) 두 전형 조회 추가
공고 상세조회 (지원자 메인페이지편) 두 전형 조회 추가
채용담당자 사이드바, 인터뷰스케줄리스트페이지 z-index 수정
<br>
> [#535][Refactor] 공고등록 및 조회 채용절차 개선

- cicd/k8s/batch/interviewInfo-cronJob.yml
closed #537 
<br>
CICD 테스트
<br>
백엔드 배포 테스트
<br>
> [#537][Batch] CICD 테스트

- cicd/k8s/batch/resumeResult-cronJob.yml
closed #537 
<br>
CICD 테스트
<br>
배치 배포 테스트
<br>
> [[#537][Batch] CICD 테스트

- backend/src/main/java/com/sabujaks/irs/global/security/filter/JwtFilter.java
- backend/src/main/java/com/sabujaks/irs/global/security/filter/LoginFilter.java
closed #548 
<br>
지원자&면접진 화상 면접방 참여시 인증 방식을 수정
<br>
1. VITOKEN 발급 안함 내부적으로 UserDetails에 권한을 담음
<br>
> [#548][Fix] 화상 면접방 접근 제어 수정

- backend/batch/src/main/java/com/example/batch/job/SendEmailFinalResultConfig.java
- backend/batch/src/main/java/com/example/batch/processor/EmailFinalResultProcessor.java
- backend/batch/src/main/java/com/example/batch/reader/EmailReader.java
- backend/batch/src/main/resources/templates/FinalResultAcceptEmail.html
- backend/batch/src/main/resources/templates/FinalResultRejectEmail.html
closed #565 
<br>
최종결과 배치처리 추가했습니다.
<br>
- 최종결과 processor 추가
- 최종결과 reader 추가
- 최종결과 이메일 템플릿 추가
<br>
> [#565][Batch] 최종결과 배치 수정

- frontend/src/components/seeker/PreferentialEmpComponent.vue
- frontend/src/pages/recruiter/resume/ResumeDetailPage.vue
- frontend/src/pages/seeker/mypage/MypageIntegrationeResumePage.vue
- frontend/src/pages/seeker/resume/ResumeDetailPage.vue
closed #411 
<br>
지원자 지원서 등록 페이지, 지원서 상세 페이지 개선
<br>
지원서 상세 조회 페이지 포트폴리오 url 부분 변경
취업우대&병역 컴포넌트에서 업데이트 되는 부분에서 체크한 값이 누락되는 경우가 있어서 버튼 누를 때마다 값 업데이트 되게 수정
<br>
> [#411][Refactor] 지원자 지원서 관련 이지 수정

- backend/batch/src/main/java/com/example/batch/writer/EmailWriter.java
closed #570 
<br>
최종결과 배치처리 저장 로직 수정했습니다.
<br>
- 최종결과 저장 로직 수정
<br>
> [#570][Feat] 배치 결과 저장 로직 수정

- backend/api/src/main/java/com/example/api/domain/resume/service/ResumeService.java
- backend/api/src/main/java/com/example/api/global/common/aspect/ExecutionTimeAspect.java
closed: #515 
<br>
메소드 실행시간 측정을 위한 Aspect 클래스 작성
<br>
메소드 실행시간 측정을 위한 Aspect 클래스 추가
검색, 공고에 지원한 지원서 상세 조회 메소드 시간 측정 어노테이션 추가
> [#515][Refactor] 실행시간 측정 어노테이션 추가

- backend/api/build.gradle
- backend/api/src/main/java/com/example/api/ApiApplication.java
- backend/api/src/main/java/com/example/api/global/config/SecurityConfig.java
- backend/api/src/main/java/com/example/api/global/security/filter/JwtFilter.java
- backend/api/src/main/java/com/example/api/global/security/filter/LoginFilter.java
- backend/api/src/main/java/com/example/api/global/security/oauth2/OAuth2AuthenticationSuccessHandler.java
- backend/api/src/main/java/com/example/api/global/utils/JwtUtil.java
- backend/api/src/main/resources/application.yml
- backend/common/build.gradle
- backend/common/src/main/java/com/example/common/domain/auth/model/entity/RefreshToken.java
- backend/common/src/main/java/com/example/common/domain/auth/repository/RefreshTokenRepository.java
- backend/common/src/main/java/com/example/common/global/config/RedisConfig.java
- backend/common/src/main/resources/application.yml
- cicd/docker-compose.yml
- cicd/redis/redis.conf
closed #521
<br>
dev-redis 브랜치에 올렸던 리프레시토큰과 레디스 관련 변경부분 dev-batch 브랜치에 추가했습니다.
<br>
레디스 관련 설정 파일 추가
로그인 필터와 jwt관련 파일 추가
<br>
> [#521][Refector] refresh token & redis 추가

- backend/api/src/main/java/com/example/api/domain/resume/controller/ResumeController.java
- backend/api/src/main/java/com/example/api/domain/resume/service/ResumeService.java
closed #583 
<br>
지원자와 채용담당자가 지원서를 상세 조회 할 때 접근 권한 예외처
<br>
지원자는 자신이 등록한 지원서만 상세 조회 가능
채용담당자는 자신이 등록한 공고에 등록한 지원서만 상세 조회 가능 하도록 수정
<br>
> [#583][Refactor] 지원서 상세 조회 접근 예외처리

- frontend/src/pages/seeker/auth/SeekerLoginPage.vue
closed #585 
<br>
지원자 로그인 페이지 예외처리 진행했습니다.
<br>
- 지원자 로그인 페이지 email=true -> 토스트메세지 출력
- 지원자 로그인 페이지 error=true -> 토스트메세지 출력
<br>
> [#585][Refactor] 지원자 로그인 페이지 예외처리

- frontend/src/assets/css/grid.css
- frontend/src/components/recruiter/InterviewEvaluateResult.vue
- frontend/src/components/recruiter/InterviewScheduleList.vue
- frontend/src/components/recruiter/InterviewScheduleMain.vue
- frontend/src/components/recruiter/MainHeaderComponent.vue
- frontend/src/components/recruiter/ReScheduleList.vue
- frontend/src/pages/recruiter/announce/AnnounceMainPage.vue
- frontend/src/pages/recruiter/interview-schedule/ReScheduleMainPage.vue
- frontend/src/pages/recruiter/resume/ResumeListPage.vue
- frontend/src/pages/recruiter/resume/ResumeMainPage.vue
- frontend/src/pages/recruiter/total-process/TotalProcessListPage.vue
- frontend/src/pages/recruiter/total-process/TotalProcessMainPage.vue
- frontend/src/stores/UseResumeStore.js
closed #593 
<br>
페이지 디자인 개선
<br>
- 헤더 디자인 수정
- 페이징 버튼 활성화 상태 디자인 수정
<br>
> [#593][Refactor] recruiter 헤더 수정 & 페이징 활성화 디자인 수정

- frontend/src/components/recruiter/MainHeaderComponent.vue
closed #595
<br>
페이지 디자인 개선
<br>
- 헤더 디자인 수정
- 헤더 redirect url 수정
<br>
> [#595][Refactor] recruiter 헤더 수정

- backend/api/src/main/java/com/example/api/global/security/filter/JwtFilter.java
- backend/api/src/main/java/com/example/api/global/utils/JwtUtil.java
closed #521
<br>
토큰관련 만료여부 수정했습니다.
<br>
토큰 시간 변경, Access Token 만료 여부 조건 수정
<br>
> [#521][Refactor] 토큰관련 만료여부 수정

- backend/api/src/main/java/com/example/api/domain/total_process/service/TotalProcessService.java
- backend/api/src/main/java/com/example/api/domain/video_interview/model/request/VideoInterviewRequest.java
- backend/api/src/main/java/com/example/api/domain/video_interview/service/VideoInterviewService.java
- backend/api/src/main/java/com/example/api/global/common/exception/GlobalExceptionHandler.java
- backend/api/src/main/java/com/example/api/global/common/responses/BaseResponseMessage.java
- backend/api/src/main/java/com/example/api/global/config/SecurityConfig.java
- backend/api/src/main/java/com/example/api/global/security/AccessControlService.java
- backend/api/src/main/java/com/example/api/global/security/CustomUserDetailService.java
- backend/api/src/main/java/com/example/api/global/security/CustomUserDetails.java
- backend/api/src/main/java/com/example/api/global/security/filter/JwtFilter.java
- backend/api/src/main/java/com/example/api/global/security/filter/LoginFilter.java
- frontend/src/components/video-interview/UserVideo.vue
- frontend/src/components/video-interview/VideoInterviewHeaderComponent.vue
- frontend/src/pages/recruiter/total-process/TotalProcessListPage.vue
- frontend/src/pages/video-interview/VideoInterviewMainPage.vue
- frontend/src/pages/video-interview/VideoInterviewRoomPage.vue
closed #604 
<br>
지원자&면접진 화상 면접방 참여시 인증 방식을 수정
<br>
VITOKEN 발급 안함 내부적으로 UserDetails에 권한을 담음
공고에 지원하지 않은 지원자가 해당 공고의 면접방에 접근 가능(면접방 자체가 보여지지는 않음)
url로 면접방 UUID를 탈취했을때, 접속됨
문제: 로그인시 권한 조회를 해서 Authorities에 담는데 문제가 있음
> [Refactor] 화상 면접방 접근 제어 개선

- frontend/src/main.js
- frontend/src/pages/recruiter/interview-evaluate/InterviewEvaluateFormCreatePage.vue
- frontend/src/pages/seeker/mypage/MypageMainPage.vue
- frontend/src/stores/UseAuthStore.js
#597
<br>
예외 촐력 시 페이지 이동 개선
<br>
면접평가표 생성 페이지에서 사이드바가 모달보다 위에 출력됨
- InterviewEvaluateFormCreatePage : 모달 z-index 9 -> 12로 변경
인터셉터에서 401오류시 홈으로 가는 코드 주석처리
- 지원자마이페이지에서 세션만료시 로그인페이지로 이동 로직 수정
- 로그인시 id/pw오류여도 홈으로 이동 x
<br>
> [#597][Refactor] 예외 처리 이동 수정

- backend/api/src/main/java/com/example/api/domain/interview_schedule/controller/InterviewScheduleController.java
- backend/api/src/main/java/com/example/api/domain/interview_schedule/service/InterviewScheduleService.java
- backend/api/src/main/java/com/example/api/domain/resume/service/ResumeService.java
- backend/api/src/main/java/com/example/api/domain/video_interview/controller/VideoInterviewController.java
- backend/api/src/main/java/com/example/api/domain/video_interview/service/VideoInterviewService.java
- backend/api/src/main/java/com/example/api/global/utils/email/service/EmailSenderSeeker.java
- backend/api/src/main/resources/templates/InterviewConfirmOnlineEmail.html
- backend/api/src/main/resources/templates/InterviewNewEmail.html
- backend/common/src/main/java/com/example/common/domain/interview_schedule/repository/InterviewScheduleRepository.java
- backend/common/src/main/java/com/example/common/domain/interview_schedule/repository/querydsl/InterviewScheduleDslRepository.java
- backend/common/src/main/java/com/example/common/domain/total_process/repository/TotalProcessRepository.java
closed #607 
<br>
인터뷰 일정 생성과정에서 인터뷰 차수에 따른 지원자 조회 로직 변경했습니다.
<br>
- InterviewScheduleRepository 변경
- InterviewScheduleReadAll 변경
- InterviewScheduleGetSeekerList 변경
<br>
> [#607][Refactor] 인터뷰 차수에 따른 지원자 조회 로직 수정

- frontend/src/components/recruiter/InterviewScheduleMain.vue
- frontend/src/pages/recruiter/interview-schedule/InterviewScheduleListPage.vue
- frontend/src/stores/UseInterviewScheduleStore.js
closed #609 
<br>
인터뷰 일정 생성과정에서 인터뷰 차수에 따른 지원자 조회 로직 변경했습니다.
<br>
- InterviewScheduleStore 변경
- InterviewScheduleListPage 변경
- InterviewScheduleList Component 변경
<br>
> [#609][Refactor] interview-schedule 차수에 따른 지원자 조회 로직 변경

- frontend/src/pages/recruiter/auth/RecruiterSignupPage.vue
- frontend/src/pages/seeker/auth/SeekerSignupPage.vue
closed #611 
<br>
지원자, 채용담당자 회원가입 페이지 개선
<br>
지원자 주소 입력 칸 추가
네이버 소셜로그인 버튼 삭제
채용담당자 프로필 이미지 입력 삭제
회원가입 성공 후 로그인 페이지로 리다이렉트
<br>
> [#611][Refactor] 회원가입 페이지 개선

- backend/api/src/main/java/com/example/api/domain/interview_schedule/service/InterviewScheduleService.java
- backend/api/src/main/java/com/example/api/domain/system/DataInit.java
- backend/api/src/main/java/com/example/api/global/utils/email/service/EmailSendEstimator.java
- backend/api/src/main/resources/templates/EstimatorEmail.html
closed #613 
<br>
인터뷰 일정 생성시 면접관 이메일 전송
<br>
프리메이커로 비동기 이메일 전송
면접관 이메일 전송 템플릿 추가
테스트시에도 면접관 이메일은 실제 사용하는 이메일을 사용해야됨
<br>
> [#613][Refactor] 인터뷰 일정 생성시 면접관 이메일 전송

- backend/api/src/main/java/com/example/api/domain/interview_schedule/service/InterviewScheduleService.java
- backend/api/src/main/java/com/example/api/global/utils/email/service/EmailSendEstimator.java
- backend/common/src/main/java/com/example/common/domain/auth/model/entity/Estimator.java
- frontend/src/components/seeker/SeekerHeaderComponent.vue
- frontend/src/pages/estimator/auth/EstimatorLoginPage.vue
- frontend/src/router/index.js
closed #602 
<br>
화상 면접방 페이지 개선 및 면접관 로그인 페이지 추가
<br>
공고UUID 링크로 이메일을 이용해 접속시 면접관, 지원자는 로그인 되지 않으면 메인으로 리다이렉션됨
기존에 지원자로 로그인하던 방식에서 면접관로그인 링크 헤더 추가+ 면접관 로그인 페이지 생성
면접방이 생성되지 않았을때 토스트메시지 3개뜨는 오류 해결
면접방 디자인(라디오버튼 , 헤더 및 사이드바 전역 크기 통일 ) 수정
<br>
> [#602][Refactor] 화상 면접방 페이지 개선 및 면접관 로그인 페이지 추가

- backend/batch/src/main/java/com/example/batch/processor/EmailConfirmInterviewScheduleProcessor.java
- backend/batch/src/main/java/com/example/batch/processor/EmailInterviewScheduleInfoProcessor.java
closed #616  
<br>
인터뷰 일정 안내 배치 과정에서 중복 이메일에 중복 알림 전송 처리 로직 추가했습니다.
<br>
- InterviewScheduleProcessor 수정
<br>
> [#616][Refactor] 중복 이메일 처리

- cicd/k8s/batch/finalResult-cronJob.yml
- cicd/k8s/batch/interviewInfo-cronJob.yml
closed #618 
<br>
배치 실행 후, 파드 자동 삭제 옵션 추가했습니다.
<br>
- cronJob.yml  파일 수정
<br>
> [#618][Refactor] cronJob 파드 자동삭제 옵션 추가

- frontend/src/pages/seeker/mypage/MypageNotificationPage.vue
closed #624
<br>
면접일정조율 버튼이 인터뷰 일정 안내 알림 일때만 보여주게 코드 수정했습니다.
<br>
- SeekerNotificationPage 수정
<br>
> [#624][Refactor] 면접일정조율 버튼 설정

- backend/batch/src/main/java/com/example/batch/processor/EmailConfirmInterviewScheduleProcessor.java
closed #626 
<br>
인터뷰 방 안내 메일 템플릿 수정했습니다.
<br>
- InterviewConfirmEmail.html 수정
<br>
> [#626][Refactor] 인터뷰 방 안내 메일 수정

- backend/api/src/main/java/com/example/api/global/utils/email/service/EmailSenderSeeker.java
closed #628 
<br>
인터뷰 방 안내 메일 수정
<br>
- 이메일 템플릿 수정했습니다.
<br>
> [#628][Refactor] 인터뷰 방 안내 메일 수정

- backend/api/src/main/java/com/example/api/domain/auth/service/CompanyVerifyService.java
- backend/api/src/main/java/com/example/api/domain/company/controller/CompanyController.java
- backend/api/src/main/java/com/example/api/domain/total_process/service/TotalProcessService.java
- cicd/docker-compose.yml
closed #631 
<br>
k8s 시간대 변경
<br>
UTC -> KST로 변경
<br>
> [#631][Feat] k8s 시간대 변경

- frontend/src/components/recruiter/InterviewScheduleList.vue
- frontend/src/components/recruiter/InterviewScheduleMain.vue
- frontend/src/components/recruiter/ReScheduleDetail.vue
- frontend/src/pages/recruiter/interview-schedule/InterviewScheduleListPage.vue
- frontend/src/pages/recruiter/interview-schedule/InterviewScheduleMainNewPage.vue
- frontend/src/pages/recruiter/interview-schedule/ReScheduleMainPage.vue
closed #635 
<br>
면접일정조율 조회 로직 수정했습니다.
<br>
- ReScheduleList 변경
- ReScheduleMain 변경
- ReScheduleDetail 변경
<br>
> [#635][Refactor] 면접일정조율 조회 수정

- backend/api/src/main/java/com/example/api/domain/interview_schedule/service/InterviewScheduleService.java
- backend/batch/src/main/java/com/example/batch/reader/EmailReader.java
- backend/common/src/main/java/com/example/common/domain/interview_schedule/repository/ReScheduleRepository.java
closed #637 
<br>
면접일정조율 조회 로직 수정했습니다.
<br>
- InterviewScheduleService 수정
- ReScheduleRepository 수정
<br>
> [#637][Refactor] 인터뷰 일정 조율 조회 로직 수정

- backend/api/src/main/resources/templates/EstimatorEmail.html
- frontend/src/pages/seeker/auth/SeekerLoginPage.vue
- frontend/src/pages/seeker/auth/SeekerSignupPage.vue
closed #637 
<br>
로그인 페이지 변경
<br>
- 면접 평가 z-index
- 소셜로그인 삭제
- 이벤트 평가버튼 1~5 스타일 변경
- 상세 조회시 Q1 바꾸기
> [Refactor] 로그인 페이지 변경

- backend/batch/src/main/java/com/example/batch/job/VideoInterviewConfig.java
- backend/batch/src/main/java/com/example/batch/processor/EmailConfirmInterviewScheduleProcessor.java
- backend/batch/src/main/java/com/example/batch/processor/EmailFinalResultProcessor.java
- backend/batch/src/main/java/com/example/batch/processor/EmailInterviewScheduleInfoProcessor.java
- backend/batch/src/main/java/com/example/batch/reader/EmailReader.java
- backend/batch/src/main/java/com/example/batch/reader/VideoInterviewReader.java
- backend/batch/src/main/resources/templates/FinalResultAcceptEmail.html
- backend/common/src/main/java/com/example/common/domain/alarm/repository/AlarmRepository.java
closed #643 
<br>
화상면접방 안내 배치 로직 수정했습니다.
최종 합격 템플릿 추가했습니다.
<br>
- 최종합격 템플릿 내용 추가
- 알람 중복 여부 로직 수정
- 화상면접방 안내 배치 로직 수정
<br>
> [#643][Refactor] 인터뷰 일정 확정 로직 수정 및 탬플릿 수정

- backend/batch/src/main/java/com/example/batch/reader/EmailReader.java
- backend/batch/src/main/java/com/example/batch/reader/VideoInterviewReader.java
- backend/batch/src/main/java/com/example/batch/writer/EmailWriter.java
closed #643 
<br>
화상면접방 안내 배치 로직 수정했습니다.
<br>
- 화상면접방 안내 배치 로직 수정
<br>
> [Refactor] 인터뷰 일정 확정 로직 수정

- frontend/src/components/recruiter/InterviewEvaluateResult.vue
closed #649
<br>
면접 평가 페이지 모달 수정
<br>
- 면접 평가 페이지 조회 모달 z-index 수정
- 오류로 다시 푸시함
<br>
> [#649][Refactor] 면접 평가 페이지 모달 수정2

- frontend/src/pages/recruiter/interview-evaluate/InterveiwEvaluateResultDetailPage.vue
- frontend/src/pages/seeker/announce/AnnounceDetailPage.vue
closed #649
<br>
면접 평가 페이지 모달 수정
<br>
- 면접 평가 페이지 조회 모달 z-index 수정
- 오류로 다시 푸시함
<br>
> [#649][Refactor] 면접 평가 페이지 모달 수정3

- backend/api/src/main/resources/templates/EstimatorEmail.html
면접관 이메일 안내 html 수정
<br>
중복된 비밀번호 안내 삭제했습니다.
> [Refactor] 면접관 이메일 안내 수정

- backend/batch/src/main/java/com/example/batch/processor/EmailConfirmInterviewScheduleProcessor.java
- backend/batch/src/main/java/com/example/batch/processor/EmailInterviewScheduleInfoProcessor.java
- backend/batch/src/main/java/com/example/batch/reader/EmailReader.java
- backend/batch/src/main/java/com/example/batch/reader/VideoInterviewReader.java
- backend/common/src/main/java/com/example/common/domain/alarm/repository/AlarmRepository.java
closed #657 
<br>
알람 중복 확인 로직 수정했습니다.
<br>
- interviewInfoProcessor 수정
- interviewConfirmProcessor 수정
- alarmRepository 수정
<br>
> [#657][Refactor] 인터뷰 일정 확정 로직 수정

- backend/api/src/main/java/com/example/api/ApiApplication.java
- backend/api/src/main/java/com/example/api/domain/resume/controller/ResumeController.java
- backend/api/src/main/java/com/example/api/global/config/ResultSendingScheduler.java
- backend/api/src/main/java/com/example/api/global/utils/email/response/ResumeResultRes.java
- backend/api/src/main/java/com/example/api/global/utils/email/service/EmailSenderSeeker.java
- backend/api/src/main/java/com/example/api/global/utils/email/service/EmailService.java
- backend/api/src/main/resources/templates/ResumeAcceptEmail.html
- backend/api/src/main/resources/templates/ResumeRejectEmail.html
- backend/common/src/main/java/com/example/common/domain/announcement/repository/AnnouncementRepository.java
closed #652 
<br>
기존 스케줄링 코드 추가
<br>
- 기존 스케줄링 코드 추가
> [#652][Refactor] 기존 일괄 처리 로직

- backend/api/src/main/java/com/example/api/domain/resume/controller/ResumeController.java
- backend/api/src/main/java/com/example/api/global/config/ResultSendingScheduler.java
closed #659 
<br>
기존 스케줄링 코드 추가
<br>
- 기존 스케줄링 코드 추가
> [#659][Refactor] 기존 일괄 처리 로직
