backend/build.gradle, backend/src/main/java/com/sabujaks/irs/IrsApplication.java, backend/src/main/java/com/sabujaks/irs/domain/auth/controller/AuthController.java, backend/src/main/java/com/sabujaks/irs/domain/auth/model/entity/CompanyVerify.java, backend/src/main/java/com/sabujaks/irs/domain/auth/model/entity/Recruiter.java, backend/src/main/java/com/sabujaks/irs/domain/auth/model/request/CompanyVerifyReq.java, backend/src/main/java/com/sabujaks/irs/domain/auth/model/request/CrnApiReq.java, backend/src/main/java/com/sabujaks/irs/domain/auth/model/request/RecruiterSignupReq.java, backend/src/main/java/com/sabujaks/irs/domain/auth/model/response/AuthSignupRes.java, backend/src/main/java/com/sabujaks/irs/domain/auth/model/response/CompanyVerifyRes.java, backend/src/main/java/com/sabujaks/irs/domain/auth/model/response/CrnApiRes.java, backend/src/main/java/com/sabujaks/irs/domain/auth/repository/CompanyVerifyRepository.java, backend/src/main/java/com/sabujaks/irs/domain/auth/service/AuthService.java, backend/src/main/java/com/sabujaks/irs/domain/auth/service/CompanyVerifyService.java, backend/src/main/java/com/sabujaks/irs/domain/auth/service/EmailVerifyService.java, backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java, backend/src/main/java/com/sabujaks/irs/global/feign_client/CrnApiFeignClient.java, backend/src/main/java/com/sabujaks/irs/global/security/CustomUserDetailService.java, backend/src/main/java/com/sabujaks/irs/global/security/CustomUserDetails.java, backend/src/main/java/com/sabujaks/irs/global/security/filter/JwtFilter.java, backend/src/main/java/com/sabujaks/irs/global/security/filter/LoginFilter.java, backend/src/main/resources/application.yml
closed: #3  
<br>
채용담당자 기업 인증 기능 개발
<br>
채용담당자가 회원가입시 기업 인증요청을 보내면 기업인증 컨트롤러가 사업자 진위 여부 확인 API 호출
진위 여부 확인 후 API 요청파라미터와 채용담당자 이메일을 기업인증 테이블에 저장
채용담당자의 이메일이 기업인증 테이블에 존재한다면 채용 담당자의 회원가입 진행
<br>
=> [#3][Feat] 채용담당자 기업 인증 개발

backend/src/main/java/com/sabujaks/irs/domain/announce/controller/AnnounceController.java, backend/src/main/java/com/sabujaks/irs/domain/announce/model/entity/Announcement.java, backend/src/main/java/com/sabujaks/irs/domain/announce/model/entity/CustomForm.java, backend/src/main/java/com/sabujaks/irs/domain/announce/model/entity/CustomLetterForm.java, backend/src/main/java/com/sabujaks/irs/domain/announce/model/request/CustomFormReq.java, backend/src/main/java/com/sabujaks/irs/domain/announce/model/response/CustomFormRes.java, backend/src/main/java/com/sabujaks/irs/domain/announce/repository/AnnounceRepository.java, backend/src/main/java/com/sabujaks/irs/domain/announce/repository/CustomFormRepository.java, backend/src/main/java/com/sabujaks/irs/domain/announce/repository/CustomLetterFormRepository.java, backend/src/main/java/com/sabujaks/irs/domain/announce/service/AnnounceService.java, backend/src/main/java/com/sabujaks/irs/domain/auth/model/entity/Recruiter.java, backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
closed: #32 
<br>
도메인에 announce 폴더를 추가하여 공고 등록에 관련된 엔티티( 공고, 커스텀폼, 커스텀자기소개서폼)를 만들었음
지원서 폼 선택 시, base_info 테이블을 사용하기로 했으므로 각 폼의 코드가 리스트로 들어가도록 서비스를 개발함
<br>
지원서 폼 조립 기능
<br>
<br>
=> [Feat] 채용담당자 공고 등록 stpe2 지원서 폼 조립 기능

backend/build.gradle, backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/controller/InterviewScheduleController.java, backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/entity/InterviewSchedule.java, backend/src/main/java/com/sabujaks/irs/domain/video_interview/controller/VideoInterviewController.java, backend/src/main/java/com/sabujaks/irs/domain/video_interview/mdoel/entity/VideoInterviewRoom.java, backend/src/main/java/com/sabujaks/irs/domain/video_interview/mdoel/request/VideoInterviewRoomCreateReq.java, backend/src/main/java/com/sabujaks/irs/domain/video_interview/mdoel/response/VideoInterviewRoomCreateRes.java, backend/src/main/java/com/sabujaks/irs/domain/video_interview/repository/VideoInterviewRepository.java, backend/src/main/java/com/sabujaks/irs/domain/video_interview/service/VideoInterviewService.java, backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java, backend/src/main/java/com/sabujaks/irs/global/config/OpenViduConfig.java, backend/src/main/resources/application.yml, cicd/docker-compose.yml, cicd/nginx/default.conf, frontend/package-lock.json, frontend/package.json, frontend/src/components/video-interview/OvVideo.vue, frontend/src/components/video-interview/UserVideo.vue, frontend/src/const.js, frontend/src/pages/recruiter/video-interview/VideoInterViewTest1Page.vue, frontend/src/pages/recruiter/video-interview/VideoInterViewTest2Page.vue, frontend/src/router/index.js, frontend/src/stores/UseVideoInterviewStore.js
closed: #55   
<br>
채용담당자 화상 면접방 생성 기능 개발
<br>
1. OpenVidu를 사용해 화상 면접 기능을 구현, 기본적으로 제공하는 소켓 기능을 이용해 화상 면접방을 생성
2. 화상 면접방을 생성하고, 이와 관련된 추가 데이터를 VideoInterviewRoom테이블에 저장
3. VideoInterviewRoom Entity, DTO, Cotnroller, Service를 구현, 연관관계 매핑
4. 면접 일정을 생성하고 면접방을 생성할때 UUID를 생성해 SeesionId로 화상 면접방의 식별자로서 등록
5. 인증 방식이 없으면 누구나 면접방에 참여가 가능하므로 면접 시간대별 지원자 참여용 비밀번호를 생성
6. Vue에 테스트 페이지 생성
=> [#55][Feat] 채용담당자 화상 면접방 생성 개발

backend/src/main/java/com/sabujaks/irs/domain/announce/controller/AnnounceController.java, backend/src/main/java/com/sabujaks/irs/domain/announce/model/entity/Announcement.java, backend/src/main/java/com/sabujaks/irs/domain/announce/model/entity/CustomLetterForm.java, backend/src/main/java/com/sabujaks/irs/domain/announce/model/request/CustomFormReq.java, backend/src/main/java/com/sabujaks/irs/domain/announce/model/response/CustomFormRes.java, backend/src/main/java/com/sabujaks/irs/domain/announce/service/AnnounceService.java, backend/src/main/java/com/sabujaks/irs/domain/data_init/repository/BaseInfoRepository.java
closed: #112 
<br>
공고 등록 과정 중 자기소개서 문항 추가에 대한 부분을 개발함
지원서 폼 조립 서비스에 자기소개서 dto까지 추가하여 한번에 저장되도록 수정함
<br>
채용담당자 공고 등록 중 step2 지원서 폼 등록과 자기소개서 문항 추가 등록
공고 entity에 공고 등록시 자동생성되는 uuid 추가 -> 공고등록 step1 기능은 아직 개발되지 않아 uuid 저장은 추후 확인 예정
<br>
<br>
=> [Feat] 채용담당자 자기소개서 등록 및 지원서 폼 코드 수정

frontend/src/components/recruiter/InterviewScheduleList.vue, frontend/src/components/recruiter/InterviewScheduleMain.vue, frontend/src/components/recruiter/MainSideBarComponent.vue, frontend/src/pages/recruiter/interview-schedule/InterviewScheduleMainExp.vue, frontend/src/pages/recruiter/interview-schedule/InterviewScheduleMainNew.vue, frontend/src/router/index.js
closed #52 
<br>
채용담당자는 신입과 경력의 면접 일정을 각각 조회할 수 있습니다.
면접일정생성 기능을 버튼을 따로 분리했습니다.
<br>
- 면접 초기 메인화면(공고리스트) 생성
- 각 공고 클릭시, 해당 공고에 해당하는 면접일정 리스트 페이지 생성
- 면접 일정 생성 버튼 생성
<br>
<br>
=> [#52][Feat] 면접 일정 설계 변경

backend/src/main/java/com/sabujaks/irs/domain/announce/model/entity/Announcement.java, backend/src/main/java/com/sabujaks/irs/domain/announce/service/AnnounceService.java, backend/src/main/java/com/sabujaks/irs/domain/data_init/repository/BaseInfoRepository.java, backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
#31
<br>
공고 등록 후 지원서 폼 등록 부분에서 중복되는 코드와 필요없는 반복문을 처리했음
base_info 테이블 조회 시 쓰는 쿼리문을 그룹이름과 코드로 한번에 조회하는 방식으로 개선함.
<br>
공고 등록후 지원서 폼 조립 서비스 코드 개선
<br>
<br>
=> [Fix] 공고등록 기능 코드 수정 및 쿼리문 개선

backend/src/main/java/com/sabujaks/irs/domain/resume/controller/ResumeController.java, backend/src/main/java/com/sabujaks/irs/domain/resume/model/entity/Resume.java, backend/src/main/java/com/sabujaks/irs/domain/resume/model/entity/ResumeInfo.java, backend/src/main/java/com/sabujaks/irs/domain/resume/model/request/ResumeSubmitReq.java, backend/src/main/java/com/sabujaks/irs/domain/resume/repository/ResumeInfoRepository.java, backend/src/main/java/com/sabujaks/irs/domain/resume/service/ResumeService.java, backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
closed: #133
<br>
지원자 지원서 등록 6 기능 개발 완료
<br>
1. 마이페이지 -> 지원서등록 (통합 지원서)
통합 지원서 등록 여부 확인(1개만 가능) -> 지원 정보 저장 -> 인적사항 저장 -> (반복) 맞춤코드에 해당하는 각 테이블에 정보 저장 후 맞춤 지원정보 저장
* 지원정보 테이블에 통합 지원서인지 아닌지 파악을 위해 통합여부 컬럼 추가
2. 공고 상세 -> 지원서등록
지원 정보 저장 -> 인적사항 저장 -> (반복) 맞춤코드에 해당하는 각 테이블에 정보 저장 후 맞춤 지원정보 저장 -> 공고지원서 저장
* 공고지원서 테이블에 지원서 제목, 지원 날짜 컬럼 추가
<br>
<br>
=> [#133][Feat] 지원자 지원서 등록6 기능 개발 완료

backend/src/main/java/com/sabujaks/irs/domain/announcement/controller/AnnouncementController.java, backend/src/main/java/com/sabujaks/irs/domain/auth/controller/AuthController.java, backend/src/main/java/com/sabujaks/irs/domain/auth/repository/EmailVerifyRepository.java, backend/src/main/java/com/sabujaks/irs/domain/auth/service/AuthService.java, backend/src/main/java/com/sabujaks/irs/domain/auth/service/EmailVerifyService.java, backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/service/InterviewEvaluateService.java, backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
closed #27 
<br>
회원 비활성화(탈퇴) 기능 개발
<br>
1. AuthService에 editPassword 메소드 추가, CustomUserDetails의 ROLE로 채용담당자, 지원자에 대해 회원 탈퇴 기능 개발
2. 지원자, 채용담당자의 계정을 비활성화
3. 계정 비활성화시(enabled(0) inactive(1)
4. 재 회원가입 시: enabled(0) inactive(0)
5. 소셜로그인시: 이메일 검증 값은 지우지 않음
6. 검증 이메일 전송 서비스 변경(계정복구와 신규회원가입을 나눔)
7. 회원가입 서비스 및 응답 변경
=> [#27][Feat] 회원 탈퇴 개발

backend/src/main/java/com/sabujaks/irs/domain/resume/controller/ResumeController.java, backend/src/main/java/com/sabujaks/irs/domain/resume/model/response/ResumeReadRes.java, backend/src/main/java/com/sabujaks/irs/domain/resume/repository/ResumeInfoRepository.java, backend/src/main/java/com/sabujaks/irs/domain/resume/repository/ResumeRepository.java, backend/src/main/java/com/sabujaks/irs/domain/resume/service/ResumeService.java, backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java, backend/src/main/java/com/sabujaks/irs/global/config/SecurityConfig.java
closed: #44 
<br>
지원자 또는 채용담당자가 공고에 지원한 지원자의 지원서를
<br>
공고지원서(resume) idx로 공고에 지원한 지원자의 지원서를 상세 조회한다.'
해당 기능은 지원자와 채용담당자가 모두 사용할 예정이라서 security config에 해당 url에 접근 가능한 role에 ROLE_SEEKER, ROLE_RECRUITER 추가
조회 데이터
1. 인적사항
2. 지원정보 맞춤 코드
3. 2에서 조회한 맞춤 코드에 해당하는 해당 지원자의 지원 정보
<br>
<br>
=> [#44][Feat] 지원서 상세 조회 개발 완료

backend/src/main/java/com/sabujaks/irs/domain/announcement/controller/AnnouncementController.java, backend/src/main/java/com/sabujaks/irs/domain/announcement/model/response/AnnouncementReadAllRes2.java, backend/src/main/java/com/sabujaks/irs/domain/announcement/repository/AnnouncementRepository.java, backend/src/main/java/com/sabujaks/irs/domain/announcement/service/AnnouncementService.java, backend/src/main/java/com/sabujaks/irs/domain/auth/model/response/RecruiterRes.java, backend/src/main/java/com/sabujaks/irs/domain/auth/model/response/SeekerInfoGetRes.java, backend/src/main/java/com/sabujaks/irs/domain/data_init/DataInit.java, backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/controller/InterviewScheduleController.java, backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/entity/InterviewSchedule.java, backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/entity/Team.java, backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/response/InterviewParticipateReadRes.java, backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/response/InterviewScheduleRes.java, backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/repository/InterviewParticipateRepository.java, backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/repository/InterviewScheduleRepository.java, backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/service/InterviewScheduleService.java, backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
closed #191 
<br>
로그인한 recruiter 정보로 등록된 공고 조회 기능 개발했습니다.
해당 공고에 등록된 각각의 면접일정 조회 기능 개발했습니다.
<br>
지원자 페이지에서 보는 공고 전체 조회에서 각 공고 클릭 시 필요한 상세조회.
- recruiter 로그인한 정보 기반 공고 조회 개발
- 공고에 등록된 각각의 면접일정 조회 개발
- interviewschedule에 team 연관관계 추가
- baseresponse 추가
<br>
<br>
=> [#191][Feat] 면접일정 공고 리스트 조회 & 면접 리스트 조회

backend/src/main/java/com/sabujaks/irs/domain/resume/model/response/ResumeReadSubmitInfoRes.java, backend/src/main/java/com/sabujaks/irs/domain/resume/service/ResumeService.java, backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
closed: #157 
<br>
지원자가 공고 상세에서 지원서 등록 클릭 시 공고를 등록한 채용 담당자가 선택한 지원서 항목과 자기소개서 맞춤 양식을 조회하고, 지원자가 등록한 통합 지원서가 있을 때만 조회하게 수정
<br>
응답 dto에 통합 지원서 등록 여부를 추가
<br>
<br>
=> [#157][Fix] 지원서 제출 페이지 진입 시 필요한 데이터 조회 수정

backend/src/main/java/com/sabujaks/irs/domain/auth/model/entity/Seeker.java, backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/controller/InterviewEvaluateController.java, backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/model/entity/InterviewEvaluate.java, backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/model/entity/InterviewEvaluateResult.java, backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/model/request/InterviewEvaluateCreateReq.java, backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/model/response/InterviewEvaluateCreateRes.java, backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/repository/InterviewEvaluateFormRepository.java, backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/repository/InterviewEvaluateRepository.java, backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/service/InterviewEvaluateService.java, backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/entity/InterviewParticipate.java, backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/entity/InterviewSchedule.java, backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/repository/InterviewParticipateRepository.java, backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
closed #197
<br>
면접관 화상 면접 평가 제출 기능을 개발
<br>
1. findBySeekerEmailAndEstimatorIdxAndInterviewScheduleUUID 메서드를 사용해 인터뷰 참여자 찾기
2. findByAnnouncementUUID를 통해 인터뷰 평가 폼을 가져오고, 없으면 예외
3. findByInterviewParticipateIdx로 해당 인터뷰 참여자에 대한 기존 평가가 있는지 확인
4. 기존 평가가 있을 경우, 새로운 평가 데이터를 DTO에서 가져와 InterviewEvaluateResult, nterviewEvaluate 업데이트
5. 기존 평가가 없을 경우, 새로운 InterviewEvaluateResult와 InterviewEvaluate 객체를 생성해 저장
=> [#197][Feat] 면접관 지원자 화상 면접 평가 생성 개발

backend/src/main/java/com/sabujaks/irs/domain/resume/controller/ResumeController.java, backend/src/main/java/com/sabujaks/irs/domain/resume/model/entity/Resume.java, backend/src/main/java/com/sabujaks/irs/domain/resume/model/request/ResumeUpdateDocPassedReq.java, backend/src/main/java/com/sabujaks/irs/domain/resume/model/response/ResumeReadRes.java, backend/src/main/java/com/sabujaks/irs/domain/resume/model/response/ResumeUpdateDocPassedRes.java, backend/src/main/java/com/sabujaks/irs/domain/resume/service/ResumeService.java, backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
closed: #46 
<br>
채용 담당자가 공고에 지원한 지원자의 지원서를 상세 조회하고 페이지에서 서류 합격 또는 불합격 버튼을 클릭해서 서류 결과 처리
<br>
인턴·대외활동, 해외경험, 어학 테이블 생성 및 테이블에 데이터 저장
공고 지원서 엔티티에 서류 결과 컬럼추가 (docPassed)
서류 결과 컬럼의 기본값은 null이고, 채용 담당자가 지원서 상세 조회 페이지에서 합격(1) 또는 불합격(2) 버튼을 눌렀을 때 공고 지원서의 서류 결과 값 업데이트
한번 선택하면 서류 결과 바꿀 수 없다.
<br>
<br>
=> [#46][Feat] 채용 담당자 서류 합불 개발 완료

backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/controller/InterviewEvaluateController.java, backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/model/response/InterviewEvaluateReadAllRes.java, backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/model/response/InterviewEvaluateReadRes.java, backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/service/InterviewEvaluateService.java, backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
closed #56 
<br>
채용담당자 화상 면접 평가 목록 조회 기능 개발
<br>
1.  announceIdx에 해당하는 공고(Announcement)를 announcementRepository에서 찾아옴, 없으면 예외
2. 조회된 공고의 채용담당자 이메일과 현재 사용자(customUserDetails)의 이메일을 비교해 일치하지 않으면 예외
3. 공고 idx로 interviewScheduleRepository에서 면접 일정을 조회, 조회된 면접 일정에 해당하는 면접 참여자 리스트 가져옴
4. 각 면접 참여자에 대해 interviewEvaluateRepository에서 평가 데이터를 조회 및 반환
=> [#56][Feat] 채용담당자 화상 면접 평가 목록 조회 개발 완료

backend/src/main/java/com/sabujaks/irs/domain/announcement/service/AnnouncementService.java, backend/src/main/java/com/sabujaks/irs/domain/company/controller/CompanyController.java, backend/src/main/java/com/sabujaks/irs/domain/company/model/entity/Company.java, backend/src/main/java/com/sabujaks/irs/domain/company/model/response/CompanyReadRes.java, backend/src/main/java/com/sabujaks/irs/domain/company/repository/CompanyImgRepository.java, backend/src/main/java/com/sabujaks/irs/domain/company/service/CompanyService.java, backend/src/main/java/com/sabujaks/irs/domain/data_init/DataInit.java, backend/src/main/java/com/sabujaks/irs/domain/data_init/controller/BaseInfoController.java, backend/src/main/java/com/sabujaks/irs/domain/data_init/model/entity/BaseInfo.java, backend/src/main/java/com/sabujaks/irs/domain/data_init/model/response/CategoryRes.java, backend/src/main/java/com/sabujaks/irs/domain/data_init/model/response/SubcategoryRes.java, backend/src/main/java/com/sabujaks/irs/domain/data_init/repository/BaseInfoRepository.java, backend/src/main/java/com/sabujaks/irs/domain/data_init/service/BaseInfoService.java, backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
closed #18
<br>
채용담당자 기업 정보 조회 기능 개발 및 관련 코드 수정
<br>
[기업 등록 조회] 기능 개발 수정
백엔드
기업 정보 조회 -> 조회 메소드 추가, 이미 등록한 기업이 있다면 모든 정보 넘겨줌
등록한 기업이 없다면 필수 정보인 기업인증정보만 넘겨줌 
기업 정보 등록 -> 파일 등록에 썼던 메소드 multipleUpload로 변경, 기업idx 매개변수 추가
기준 정보 컨트롤러, 서비스 추가 ->
기준 정보(BaseInfo) 테이블에서 카테고리별 코드 데이터 조회하여 대분류, 소분류 리스트 출력하는 메소드 추가
<br>
=> [#18][Feat] 채용담당자 기업 관련 기능, 기준 코드 조회 기능 개발

frontend/src/pages/recruiter/resume/ResumeDetailPage.vue, frontend/src/pages/recruiter/resume/ResumeMainPage.vue, frontend/src/stores/UseResumeStore.js
Fixes: #79 
<br>
채용담당자가 등록한 공고 목록을 조회하고, 공고를 선택하면 해당 공고에 지원한 지원자 목록 조회 페이지로 이동
<br>
채용담당자 idx로 조회
조회 정보
공고 idx
공고시작
공고마감
공고제목
신입/경력
지원자 수
<br>
<br>
=> [#79][Feat] 채용담당자 지원서 관리 페이지 개발 완료

frontend/src/components/recruiter/InterviewEvaluateFormMain.vue, frontend/src/components/recruiter/InterviewEvaluateResultMain.vue, frontend/src/components/recruiter/MainSideBarComponent.vue, frontend/src/pages/recruiter/interview-evaluate/InterveiwEvaluateResultDetailPage.vue, frontend/src/pages/recruiter/interview-evaluate/InterviewEvaluateFormPage.vue, frontend/src/pages/recruiter/interview-evaluate/InterviewEvaluateResultPage.vue, frontend/src/router/index.js, frontend/src/stores/UseInterviewEvaluateStore.js
closed #241 
<br>
채용담당자 화상 면접 평가 목록 조회 페이지 개발
<br>
1.  MainHeaderComponent와 MainSideBarComponent를 이용한 페이지 레이아웃 구성
2. onMounted 훅을 사용해 컴포넌트 마운트 시 면접 평가 데이터를 API에서 불러오도록 설정
3. Object.entries()를 활용하여 interviewEvaluateResult 데이터를 테이블 형식으로 출력
4. vue-toastification 라이브러리를 사용해 데이터 호출 성공 시 사용자에게 알림 메시지 표시
5. v-for를 이용해 면접 평가 결과(이름, 총점, 코멘트, 이메일)를 반복하여 테이블에 표시
=> [#241][Feat] 채용담당자 화상 면접 평가 목록 조회 페이지 개발

backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/controller/InterviewEvaluateController.java, backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/model/response/InterviewEvaluateReadRes.java, backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/model/response/InterviewEvaluateResultReadRes.java, backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/service/InterviewEvaluateService.java
closed #57 
<br>
채용담당자 화상 면접 평가 상세 조회 개발
<br>
1. announceIdx에 해당하는 공고(Announcement)를 announcementRepository에서 찾아옴, 없으면 예외
2. 조회된 공고의 채용담당자 이메일과 현재 사용자(customUserDetails)의 이메일을 비교해 일치하지 않으면 예외
3. 공고 idx로 interviewScheduleRepository에서 면접 일정을 조회, 조회된 면접 일정에 해당하는 면접 참여자 리스트 가져옴
4. 각 면접 참여자에 대해 interviewEvaluateRepository에서 평가 데이터를 조회 및 반환
5. 따로 상세 조회 컨트롤러를 만들지 않고, 목록조회시 평가항목과 평가항목별 점수를 가져오게 수정
=> [#57][Feat] 채용담당자 화상 면접 평가 상세 조회 개발

frontend/src/pages/seeker/mypage/MypageIntegrationeResumePage.vue
closed: #66 
<br>
지원자가 등록한 통합 지원서 상세 조회
<br>
통합지원서를 등록하지 않고 해당 페이지 접근 시 이미지가 없다는 에러가 뜨는 부분 수정
=> [#66][Fix] 통합 지원서 관리 페이지 에러 수정

backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/controller/InterviewEvaluateController.java, backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/model/response/InterviewEvaluateReadAllRes.java, backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/model/response/InterviewEvaluateReadRes.java, backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/repository/InterviewEvaluateRepository.java, backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/service/InterviewEvaluateService.java
closed #309 
<br>
채용담당자 화상 면접 평가 목록 조회 수정
<br>
1.  주어진 announceIdx를 이용해 채용 공고를 검색하고, 요청을 한 사용자가 해당 채용 공고의 작성자인지 검증
2. 채용 공고에 해당하는 모든 면접 스케줄을 가져오고, 각 스케줄에 참여한 면접 참여자 목록을 가져옴
3. 각 면접 참여자의 면접 평가 정보를 가져와서, 지원자 별로 평가자들이 남긴 평가 점수, 평가 항목에 대한 응답 등을 객체로 저장
4. Map 구조로, Seeker ID를 키로 사용하여 각 지원자의 면접 평가 리스트를 저장합니다. 동일 지원자의 평가가 여러 개일 경우 리스트에 추가
=> [#309][Feat] 채용담당자 화상 면접 평가 목록 조회 수정

frontend/src/components/recruiter/InterviewScheduleList.vue, frontend/src/components/recruiter/ReScheduleDetail.vue, frontend/src/pages/recruiter/interview-schedule/InterviewScheduleMainExp.vue, frontend/src/pages/recruiter/interview-schedule/InterviewScheduleMainNew.vue
#49 
<br>
채용담당자는 면접 일정이 확정되면, 이메일로 알림을 보낼 수 있다.
<br>
1. interview-list에서 list정보 전송
2. 경력, 신입 면접방 확정 이메일 전송을 위한 list 데이터 바인딩 처리
=> [#49][Feat] 면접방 생성 후 이메일 전송을 위한 데이터 바인딩 처리

frontend/src/pages/seeker/resume/ResumeSubmitPage.vue
closed: #72 
<br>
지원자가 공고에 제출할 지원서를 작성하기 위해 지원서 제출 페이지 접근 시 나는 에러 수정
<br>
지원서 항목이 없을 때 해당 페이지 접근 시 에러가 뜨는 부분 수정
=> [#72][Fix] 지원자 지원서 제출 페이지 에러 수정

backend/src/main/java/com/sabujaks/irs/domain/video_interview/service/VideoInterviewService.java, backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
closed: #146 
<br>
지원자가 공고에 제출할 지원서를 작성하기 위해 지원서 제출 페이지 접근 시 나는 에러 수정
<br>
1. OpenVidu를 사용해 화상 면접 기능을 구현
2. 스프링 시큐리티로 자기 시간대가 아니거나 자신의 면접방이 아닌경우 접근을 제한함
3. 면접관 엔티티 추가 연관관계 매핑, 면접 일정 기능 수정
4. 지원자, 채용 담당자, 면접진 공고 면접 목록 조회 및 면접방에 대한 접근제어 수행
5. 토큰 기반으로 권한을 저장하고 jwtFilter에서 권한 설정 및 Security가 권한기반 접근제어 수행
6. 지원자의권한이 ROLE_SEEKER|df9333c3-f843-4e11-a12a-ba43cfc22642|29306f9d-2407-4323-84db-7. 7c09f53722a5|2024.09.28|12:00|15:00일때 | 같은 공고라도 2024.09.28 12:00~15:00 에 진행되는 면접방에만 참가 가능
8. VideoInterviewService에서 get-access-token 요청시 권한을 조회하고, 시스템 시간과 비교해 예외처리
9. checkUserAuthorities() 메소드
- 사용자 권한을 순회하면서 입력된 AnnounceUUID와 VideoInterviewUUID가 일치하는지 확인
- 권한의 시간 범위(시작 시간 3분 전부터 종료 시간까지)가 현재 시간 내에 있는지 검증
- 유효하면 true를 반환하고, 그렇지 않으면 false를 반환하여 권한을 검증
=> [#146][Feat] 지원자 & 면접진 화상 면접방 시간대 접근 제어 개발

backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/entity/InterviewSchedule.java, backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/request/InterviewScheduleReq.java, backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/response/InterviewScheduleRes.java, backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/service/InterviewScheduleService.java
closed: #326 
<br>
채용담당자는 면접 일정등록시, 몇차 면접인지 지정할 수 있다.
<br>
1. InterviewSchedule Entity 수정
2. InterviewSchedule Service 수정
3. InterviewSchedule dto 수정
=> [#326][Feat] 면접 일정 생성 인터뷰 차수 설정 추가

backend/src/main/java/com/sabujaks/irs/domain/announcement/model/entity/Announcement.java, backend/src/main/java/com/sabujaks/irs/domain/auth/model/entity/Seeker.java, backend/src/main/java/com/sabujaks/irs/domain/interview_evaluate/service/InterviewEvaluateService.java, backend/src/main/java/com/sabujaks/irs/domain/total_process/controller/TotalProcessController.java, backend/src/main/java/com/sabujaks/irs/domain/total_process/model/entity/TotalProcess.java, backend/src/main/java/com/sabujaks/irs/domain/total_process/model/request/TotalProcessCreateReq.java, backend/src/main/java/com/sabujaks/irs/domain/total_process/model/response/TotalProcessCreateRes.java, backend/src/main/java/com/sabujaks/irs/domain/total_process/repository/TotalProcessRepository.java, backend/src/main/java/com/sabujaks/irs/domain/total_process/service/TotalProcessService.java, backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
closed: #331 
<br>
공고 지원 통합 프로세스 생성 개발
<br>
TotalProcess 엔티티, 컨트롤러, 서비스, DTO 생성
create메소드: InterveiwNum(0: 서류, 1: 1차, 2: 2차 3: 최종)으로 각 지원 프로세스 별 결과를 지원자 ID, 공고 ID로 저장
=> [#331][Feat] 공고 지원 통합 프로세스 생성 개발

backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/controller/InterviewScheduleController.java, backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/entity/InterviewParticipate.java, backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/response/TimeInfoRes.java, backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/repository/InterviewScheduleRepository.java, backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/service/InterviewScheduleService.java, backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
closed: #340 
<br>
채용담당자는 면접 일정등록시, 등록 가능한 시간대만 조회할 수 있다.
<br>
1. InterviewSchedule Controller 수정
2. InterviewSchedule Service 수정
3. TimeInfoRes dto 생성
=> [#340][Feat] 면접 일정 시간 필터링

frontend/src/pages/recruiter/resume/ResumeDetailPage.vue, frontend/src/stores/UseResumeStore.js
Fixes: #80 
<br>
채용담당자가 지원자의 지원서에 대해 서류 합격/불합격 여부 선택
<br>
채용담당자가 서류 결과를 합격 또는 불합격 처리 할 때 요청 url 변경
(기존 공고지원서의 컬럼만 변경해주었다면 total_process 테이블 생성)
<br>
<br>
=> [#80][Fix] 채용 담당자 서류 합불 엔티티 구조 변경에 의한 로직 수정

frontend/src/components/recruiter/InterviewScheduleList.vue
closed #357 
<br>
면접 일정 조회 페이지에서 방 생성 버튼과 해당 버튼이 있는 row 클릭 이벤트가 동시 실행되는 부분 수정했습니다.
<br>
- 화상 면접 방 생성 버튼 클릭시 stopPropagation 추가
<br>
=> [#357][Fix] Video Interview 생성 event 동시 실행 수정

backend/src/main/java/com/sabujaks/irs/IrsApplication.java, backend/src/main/java/com/sabujaks/irs/domain/alarm/service/AlarmService.java, backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/controller/InterviewScheduleController.java, backend/src/main/java/com/sabujaks/irs/domain/resume/controller/ResumeController.java, backend/src/main/java/com/sabujaks/irs/domain/video_interview/controller/VideoInterviewController.java, backend/src/main/java/com/sabujaks/irs/domain/video_interview/model/request/VideoInterviewCreateAllReq.java, backend/src/main/java/com/sabujaks/irs/domain/video_interview/service/VideoInterviewService.java, backend/src/main/java/com/sabujaks/irs/global/config/SchedulerConfig.java, backend/src/main/java/com/sabujaks/irs/global/utils/email/model/response/ResumeRejectRes.java, backend/src/main/java/com/sabujaks/irs/global/utils/email/service/EmailSenderEstimator.java, backend/src/main/java/com/sabujaks/irs/global/utils/email/service/EmailSenderSeeker.java, backend/src/main/java/com/sabujaks/irs/global/utils/email/service/EmailService.java, backend/src/main/resources/templates/ResumeRejectEmail.html
closed #29 
closed #30 
<br>
채용담당자는 각 채용 프로세스 결과를 이메일로 전송 및 알람으로 등록할 수 있습니다.
지원자는 해당 이메일을 템플릿을 통해서 제공받고, 도메인 내 알림페이지에서도 확인할 수 있습니다.
<br>
- 채용 프로세스 결과 템플릿 추가
- 채용 프로세스 결과(알람) 조회 로직 수정
- 화상면접방 일괄 생성 동적 스케줄링 적용
- 이메일 전송을 위한 dto 생성
- 알람 등록 로직 수정
<br>
=> [Feat] 각 채용 프로세스 결과 이메일 & 알람 일괄 전송 및 화상면접방 일괄 생성(동적스케줄링)

frontend/src/components/recruiter/MainSideBarComponent.vue, frontend/src/components/seeker/SeekerHeaderComponent.vue, frontend/src/pages/recruiter/interview-evaluate/InterviewEvaluateFormPage.vue, frontend/src/pages/recruiter/interview-evaluate/InterviewEvaluateResultPage.vue
#407 
<br>
채용담당자 페이지 사이드바 중복 메뉴 삭제했습니다.
각 페이지 좌우 여백 통일시켰습니다.(면접 평가, 면접 평가표 페이지)
<br>
채용담당자 사이드바
- 제일 하단 면접 평가 메뉴 삭제
각 페이지 여백
- 면접 평가 페이지 여백 조절
- 면접 평가표 페이지 여백 조절
<br>
=> [#407][Refactor] 채용담당자 페이지 사이드바 중복 메뉴 제거 및 각 페이지 테이블 여백 통일

backend/src/main/java/com/sabujaks/irs/domain/resume/controller/ResumeController.java, backend/src/main/java/com/sabujaks/irs/domain/resume/service/ResumeService.java, backend/src/main/java/com/sabujaks/irs/global/config/SecurityConfig.java
closed: #447 
<br>
지원자가 통합지원서 등록 페이지 진입 시 통합지원서 등록 여부를 조회하여 등록 페이지를 보여주거나 조회 페이지를 보여주기 위해 구현했는데 통합지원서 상세 조회로 대체 가능해서 삭제
<br>
<br>
=> [#447][Fix] 지원자 통합지원서 등록 여부 조회 삭제

frontend/src/pages/recruiter/announce/AnnounceRegisterStep1Page.vue, frontend/src/pages/recruiter/announce/AnnounceRegisterStep2Page.vue, frontend/src/pages/seeker/announce/AnnounceReadAllPage.vue, frontend/src/stores/UseAnnouncementStore.js, frontend/src/stores/UseCustomFormStore.js
#413
<br>
두 유저 전체 공고 관련 페이지 개선
<br>
이미지 업로드 버튼 디자인 수정
이미지 업로드 배경색 수정
이미지 업로드일때 카테고리 db에 들어가게 필수 처리 추가
공고 등록 시 복리후생 조회 디자인 변경
지원 접수 기간 날짜 부분 한 칸 밑으로 내리기
면접 횟수 -> 전형절차 자동으로 들어가게 수정
지원서 폼 조립 상단 여백 조정
지원서 폼 조립 후 /recruiter/announce 페이지로 리다이렉트
지원자 메인페이지(목록 조회) : 메인에서 공고 상세 들어갈 때 새창 뜨는 부분 수정 (새창 뜨면서 헤더가 로그아웃된 것 처럼 변경됨 -> a 태그에 타겟 삭제해서 해결)
<br>
=> [#413][Refactor] 채용담당자와 지원자 공고 관련 페이지 개선

frontend/src/components/recruiter/InterviewScheduleList.vue, frontend/src/components/recruiter/InterviewScheduleMain.vue, frontend/src/components/recruiter/ReScheduleList.vue, frontend/src/pages/recruiter/interview-schedule/InterviewScheduleListPage.vue, frontend/src/pages/recruiter/interview-schedule/InterviewScheduleMainNewPage.vue, frontend/src/pages/recruiter/interview-schedule/ReScheduleDetailPage.vue, frontend/src/pages/recruiter/interview-schedule/ReScheduleListPage.vue, frontend/src/pages/recruiter/interview-schedule/ReScheduleMainPage.vue, frontend/src/router/index.js, frontend/src/stores/UseInterviewScheduleStore.js
#462
<br>
채용담당자 인터뷰 일정 페이지 새로고침 및 redirect시 에러 해결했습니다.
채용담당자 인터뷰 일정 조율 페이지 분리했습니다.
<br>
- 인터뷰 일정 페이지 새로고침 및 redirect시 요구되는 데이터 default 셋팅
- 인터뷰 일정 조율 페이지 메인, 리스트, 상세조회 총 3개로 분리
<br>
=> [#462][Refactor] 채용담당자 인터뷰 일정 조율 및 일정 조율 관리 페이지 개선

backend/src/main/java/com/sabujaks/irs/domain/announcement/service/AnnouncementService.java, backend/src/main/java/com/sabujaks/irs/domain/resume/model/entity/PersonalInfo.java, backend/src/main/java/com/sabujaks/irs/domain/system/DataInit.java, backend/src/main/java/com/sabujaks/irs/domain/system/controller/BaseInfoController.java, backend/src/main/java/com/sabujaks/irs/domain/system/model/response/BaseInfoReadRes.java, backend/src/main/java/com/sabujaks/irs/domain/system/repository/BaseInfoRepository.java, backend/src/main/java/com/sabujaks/irs/domain/system/service/BaseInfoService.java, backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java, backend/src/main/resources/application.yml
closed #451
<br>
공고 관련 기능 로직 수정과 카테고리 부분 BaseInfo 활용 방향으로 개선
<br>
조회 시 카테고리 설명으로 나오게 백엔드 조회 코드 수정
- base_info 테이블 job_category 추가 = DataInit
- system 패키지 서비스 추가 = 코드로 BaseInfo 엔티티 조회 메서드
- announcement 패키지 서비스 수정 = 공고 상세조회 시 jobCategory 넣는 부분
근무지역 컬럼 및 다른 컬럼 몇 가지 길이 늘리기 region
이미지 업로드일 때 카테고리 db에 들어가게 수정
공고 생성 시 채용담당자 토큰없을때 null 오류 시큐리티 설정에 추가
<br>
=> [#451][Refactor] 공고 등록 및 조회 로직 개선

frontend/src/pages/recruiter/announce/AnnounceDetailPage.vue, frontend/src/pages/recruiter/announce/AnnounceMainPage.vue, frontend/src/pages/recruiter/announce/AnnounceRegisterStep1Page.vue, frontend/src/pages/recruiter/announce/AnnounceRegisterStep2Page.vue, frontend/src/pages/recruiter/company/CompanyInfoPage.vue, frontend/src/stores/UseAnnouncementStore.js, frontend/src/stores/UseBaseInfoStore.js
closed #413
<br>
채용담당자, 지원자 공고 관련 전체 페이지 개선
<br>
이미지 업로드 버튼 디자인 수정
이미지 업로드 배경색 수정
이미지 업로드일때 카테고리 db에 들어가게 필수 처리 추가
공고 등록 시 복리후생 조회 디자인 변경
지원 접수 기간 날짜 부분 한 칸 밑으로 내리기
면접 횟수 -> 전형절차 자동으로 들어가게 수정
지원서 폼 조립 상단 여백 조정
지원서 폼 조립 후 /recruiter/announce 페이지로 리다이렉트
카테고리(현재 string) 코드 넘겨주기 처리
지원자 메인페이지(목록 조회) : 메인에서 공고 상세 들어갈 때 새창 뜨는 부분 수정 (새창 뜨면서 헤더가 로그아웃된 것 처럼 변경됨 -> a 태그에 타겟 삭제해서 해결)
공고 관리 페이지에서 채용담당자가 등록한 공고 목록 조회 페이지 페이징 처리
<br>
=> [#413][Refactor] 공고 관련 전체 페이지 개선

frontend/src/pages/recruiter/announce/AnnounceDetailPage.vue, frontend/src/pages/recruiter/announce/AnnounceRegisterStep1Page.vue, frontend/src/pages/recruiter/announce/AnnounceRegisterStep2Page.vue, frontend/src/pages/recruiter/company/CompanyInfoPage.vue, frontend/src/pages/recruiter/resume/ResumeListPage.vue, frontend/src/pages/recruiter/resume/ResumeMainPage.vue, frontend/src/stores/UseCompanyStore.js, frontend/src/stores/UseCustomFormStore.js
closed #474
<br>
지원서 폼과 자기소개서 항목도 조회 가능하게 추가했습니다. 조회할 정보가 없을 시 조립페이지로 이동합니다.
<br>
공고 관리 페이지에서 공고 하나 선택 시, 이동하는 공고 상세 조회 페이지에 기능 추가
조립된 지원서 폼 확인 버튼 추가
데이터가 있으면 모달창으로 출력
데이터가 없으면 지원서 폼 조립 페이지로 리다이렉트
공고와 기업 관련 디자인 틀어진 부분 정리
지원서 관리 페이지에 호버 스타일 추가
<br>
=> [#474][Refactor] 채용담당자 공고 상세 조회 페이지 지원서 폼 조회 추가

backend/src/main/java/com/sabujaks/irs/domain/announcement/model/response/AnnouncementReadAllRes2.java, backend/src/main/java/com/sabujaks/irs/domain/announcement/service/AnnouncementService.java, backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/model/response/InterviewScheduleRes.java, backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/repository/InterviewScheduleRepository.java, backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/repository/ReScheduleRepository.java, backend/src/main/java/com/sabujaks/irs/domain/interview_schedule/service/InterviewScheduleService.java, backend/src/main/java/com/sabujaks/irs/global/common/responses/BaseResponseMessage.java
closed #465
<br>
채용담당자 인터뷰 일정 페이지(신입, 경력, 일정조율) 조회시, 생성된 면접일정 및 일정 조율 개수 표시했습니다.
<br>
- InterviewScheduleRepository 로직 추가
- ReScheduleRepository 로직 추가
- AnnouncementService readAllAnnouncement 로직 변경
- AnnouncementReadAllRes2 반환 요소 추가
<br>
=> [#483][Refactor] 채용담당자 인터뷰 일정(신입, 경력, 일정조율) 페이지 생성된 일정 개수 표시

frontend/src/components/recruiter/InterviewScheduleMain.vue
closed #485 
<br>
채용담당자 인터뷰 일정 페이지(신입, 경력, 일정조율) 조회시, 생성된 면접일정 및 일정 조율 개수 표시했습니다.
<br>
- InterviewSheduleMain 로직 수정
<br>
=> [#485][Refactor] 인터뷰 일정 페이지(신입, 경력, 일정조율)에서 이미 생성된 일정 개수 표시

backend/src/main/java/com/sabujaks/irs/domain/alarm/model/entity/Alarm.java, backend/src/main/java/com/sabujaks/irs/domain/alarm/repository/AlarmRepository.java, backend/src/main/java/com/sabujaks/irs/domain/resume/controller/ResumeController.java, backend/src/main/java/com/sabujaks/irs/domain/resume/model/entity/Resume.java, backend/src/main/java/com/sabujaks/irs/global/utils/email/model/response/ResumeResultRes.java, backend/src/main/java/com/sabujaks/irs/global/utils/email/service/EmailSenderSeeker.java, backend/src/main/java/com/sabujaks/irs/global/utils/email/service/EmailService.java, backend/src/main/resources/templates/ResumeAcceptEmail.html
closed #487 
<br>
채용담당자가 서류결과를 일괄 전송할 수 있는 로직을 개선했습니다.
기존에 전송했던 인원에 대해서는 전송하지 않고, 새롭게 추가된 인원에 대해서만 전송하게 로직을 변경했습니다.
<br>
- Alarm 엔티티 수정
- Resume 엔티티 수정
- AlarmRepository 로직 추가
- ResumeController 수정
- ResumeResultRes 정보 추가
- EmailSenderSeeker 중복 처리 로직 추가
- EmailService 로직 수정
- ResumeAcceptEmail 템플릿 추가
<br>
=> [#487][Refactor] 채용담당자 서류결과 일괄전송 로직 개선

frontend/src/pages/recruiter/resume/ResumeListPage.vue, frontend/src/stores/UseResumeStore.js
closed #489
<br>
채용담당자가 서류결과를 일괄 전송할 수 있는 로직을 개선했습니다.
기존에 로직을 전송하고 location.reload하는 부분, store에서 처리하게 수정했습니다.
<br>
- ResumeListPage toast처리 삭제
- UseResumeStore toast처리 추가
<br>
=> [#489][Refactor] 채용담당자 서류결과 일괄전송 로직 개선

backend/src/main/java/com/sabujaks/irs/domain/announcement/model/entity/Announcement.java, backend/src/main/java/com/sabujaks/irs/domain/announcement/model/request/AnnouncementCreateReq.java, backend/src/main/java/com/sabujaks/irs/domain/announcement/model/response/AnnouncementReadDetailRes.java, backend/src/main/java/com/sabujaks/irs/domain/announcement/service/AnnouncementService.java
closed #533
<br>
채용 프로세스 날짜 추가
<br>
공고에 서류전형, 전체전형 마감날짜 추가
announcement 엔티티
AnnouncementCreateReq 공고 등록시에 
AnnouncementReadDetailRes 공고 상세보기에 추가(채용담당자가 본인공고 상세조회시에만 나타나게 할 것임)
AnnouncementService 공고 등록과 공고상세조회 부분. readDetailSee, createAnnouncement
<br>
=> [#533][Refactor] 공고 채용 프로세스 날짜 추가

backend/api/src/main/java/com/example/api/domain/system/DataInit.java, backend/api/src/main/java/com/example/api/domain/total_process/service/TotalProcessService.java, cicd/docker-compose.yml
closed #600
<br>
채용담당자가 면접 1차 및 2차 평가에 대해 저장 안되는 문제 해결
<br>
엔티티 저장 추가
불합격시 연쇄 불합격처리 ex) 지원서 불합격시 1차, 2차, 최종(interviewNum=3) 불합격 처리
1차, 2차, 최종이 정해졌고, 내부적인 오류로 인한 수정 사항 발생시 1차를 수정하면 2차, 최종이 초기화됨
<br>
=> [#600][Refactor] 지원 프로세스, 면접 평가 로직 수정
